### ISSUE TITLE
sprintf is a mess

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#11]
When Perl 6 got designed, it was decided that things that needed to be broken, were broken.

I feel that `sprintf` somehow escaped that scrutiny.

Fact is that the current  nqp implementation has a number of bugs, and a number of inconsistencies.

One way forward would be to make `sprintf` completely consistent, without special cases for the value 0 or the "o" format.  But this will break a number of spectests.

Another way forward would be to just fix the bugs in the nqp implementation, making it match as much as possible to what Perl 5 is doing.

A third way forward would be to do both, but expose the logic with another name.

A fourth option would be all of the above, but with a named parameter to indicate that you want either the new consistent behaviour, or the old inconsistent behaviour.

Or perhaps there are other options still.

Why am I asking this?  Because I'm working on re-implementing `sprintf` in HLL Perl 6, which makes it faster on repeated calls with the same format.

**Comment by lizmat** [comment]
@timo suggested to have a look at https://pyformat.info/

**Comment by lizmat** [comment]
Or perhaps this work that I'm doing now, should just be an ecosystem module.

**Comment by jnthn** [comment]
I'd lean towards `sprintf` and friends behaving as format strings traditionally have (recognizing that there's no doubt been divergences in said traditions, but also plenty of agreement too). That would imply we fix places where we do something that's clearly wrong (if no other widely used implementation, say in C or Perl 5, behaves that way our `sprintf` does, we can probably safely say we're doing it wrong). For better or worse, it's the best formatting option we have in Perl 6 today, so we may as well polish it. Of course, we can do some natural extensions (for example, `%d` coping with big integers is fine).

Taking the longer view, however, I certainly don't think that `sprintf` need be the only option for formatting in Perl 6; for example, something involving adverbing interpolations with formatting directives could be quite a natural fit. I'd encourage exploration of alternatives to first take place in modules.

Whichever way an effort to create something more 6y for formatting ends up, I doubt that putting such a new behavior under the name `sprintf` would be fitting, and in fact don't expect it'd turn out as a function call at all. I also think having a well-behaved `sprintf` would ease the experience of those porting code from a wide range of other languages, or wanting to use existing knowledge of format strings. TIMTOWTDI, and offering the `sprintf` way - even if it's alongside some future other way - feels reasonable to me.

**Comment by lizmat** [comment]
Perhaps  the focus should be on being POSIX compliant as much as possible?
