### ISSUE TITLE
Apply for AWS credit

### ISSUE THREAD

**Issue by JJ** [Raku/problem-solving#116]
AWS gives one year of credit to open source projects: [here](https://aws.amazon.com/es/blogs/opensource/aws-promotional-credits-open-source-projects/). Maybe we should apply for them? We could use them for

* Hosting the blog #115 
* As a build server for Commitable
* Hosting bots
* Staging servers for infrastructure.
* Running benchmarks...

**Comment by AlexDaniel** [comment]
One year? And then what? Am I missing something? Very nice of them to use open-source movement to promote their services, but it doesn't feel like a lot of help from their side.

> Hosting the blog #115

My understanding is that we have a bunch of servers capable of doing that.

> As a build server for Commitable

This is doing just fine on my server, any problems with it?

> Hosting bots

Same

> Staging servers for infrastructure.

What does that mean exactly?

> Running benchmarks...

On virtual servers?

**Comment by JJ** [comment]
> One year? And then what? Am I missing something? Very nice of them to use open-source movement to promote their services, but it doesn't feel like a lot of help from their side.

No, you're not. You'll probably have to reapply all over again. I guess if we don't host any permanent infrastructure there, we're good if we simply don't get it. Having AWS credit is nice no matter what.

> 
> > Staging servers for infrastructure.
> 
> What does that mean exactly?

Testing deployment before you do it to the real production server.

> 
> > Running benchmarks...
> 
> On virtual servers?

Yep, why not? They're as valid as "my laptop" and you can run them every day if you want...

**Comment by rba** [comment]
Very cool. I will sign up and let you know.

**Comment by AlexDaniel** [comment]
Feel free to use this to burn cpu cycles but please don't put anything permanent on it (blogs, bots, automation, etc.).

**Comment by JJ** [comment]
> Feel free to use this to burn cpu cycles but please don't put anything permanent on it (blogs, bots, automation, etc.).

Well, we can use it to test stuff before we move it to the permanent infrastructure. Thanks, @rba

**Comment by rba** [comment]
AWS asks a lot of questions like:

```
AWS Credits for Open Source Application Form
Company Address (optional)
Country/Region (optional)
State (optional)
Postal Code (optional)
Level of AWS Usage *
Level of AWS Knowledge *
What are you looking to accomplish with the Activate credits?  * (100-200 words)
Requested amount (in USD) *
S3 Calculator URL (https://calculator.s3.amazonaws.com/index.html)  *
```

**Comment by rba** [comment]
I just asked for 500 USD. I don‘t know if we have a chance. I asked for less last time on Digitalocean and I haven‘t heard back from them after application.

**Comment by JJ** [comment]
Thanks, Roman

**Comment by rba** [comment]
Got a feedback from Amazon. I guess I didn't fully understood the form I've filled out as I have only added calculated expenses for S3 (~ 100 GB storage/10 GB up+down/10000 put+get):

```
Hello Roman,
 
This is Arun Gupta from Amazon!
 
We are reviewing your application for AWS credits for Raku / Perl 6 build/test automation. S3 calculator URL shows monthly need as $2.62 and the ask is $500. Can you help clarify the discrepancy?
 
Arun
```

@JJ or someone else, do you have experience with the AWS calculator? https://calculator.s3.amazonaws.com/index.html
May you help me to estimate the compute power and the other cloud resources we need, using the calculator for the expected use cases?
