### ISSUE TITLE
IO::Socket::INET and IO::Socket::Async need a redesign in v6.e

### ISSUE THREAD

**Issue by Kaiepi** [Raku/problem-solving#125]
How `IO::Socket::INET` and `IO::Socket::Async` were designed to handle creating and writing to sockets only makes sense when TCP is the only protocol supported. This will no longer be the case with UDP, UNIX, and raw socket support, as well as socket option support is coming soon as part of the IP6NS grant. There are three issues with the two modules' current design, some of which the design in the grant proposal failed to take into account:

- Sockets can only be created via connecting or listening for connections. Connections are optional for UDP clients, and UDP servers are just bound, rather than bound and listened on. Certain socket options (such as `SO_REUSEPORT`) cannot be used after connecting or binding, and socket options are a feature that's part of the IP6NS grant. Creating sockets, connecting, binding, and listening need separate methods to give people better control over how sockets are initialized.
- UDP sockets require an address in addition to data when sending, and raw sockets are useless without the ability to send raw data over them. There needs to be at least not one (or two in `IO::Socket::Async`'s case), but three different ways to send data over sockets.
- Ideally it would be possible for Raku to support any protocol, rather than just the ones in the IP6NS grant proposal, without requiring making any changes to Raku itself.

Many networking ecosystem modules depend on NativeCall because of shortcomings in Raku's networking design, and since breaking changes are already a part of the IP6NS grant, now would be a better time than ever to redesign `IO::Socket::INET` and `IO::Socket::Async` in such a way to heavily reduce the need to depend on C in order to deal with networking. Keep in mind #111 needs a solution that can work with the solution to this.

I'll post a proposal for how `IO::Socket::INET` and `IO::Socket::Async` could work tomorrow if redesigning them in v6.e is reasonable to do.

**Comment by jnthn** [comment]
I think changes should be *additive* rather than breaking.

**Comment by Kaiepi** [comment]
I would not propose a redesign without considering the possibility of implementing these without breaking changes first, but I didn't include part of the reasoning behind that last issue in the OP, which is mainly why this issue exists.

I never proposed support for async raw sockets because I thought they would be too complex to implement on any existing backend ourselves. This may not be the case for MoarVM; libuv's TCP and UDP functions are actually functions for *any* streaming or datagram socket, not TCP and UDP specifically. As long as all existing protocols are either streaming protocols or datagram protocols, `IO::Socket::INET` and `IO::Socket::Async` could be made entirely agnostic of the protocol used.

While I think it would actually be ideal for this to be handled additively for `IO::Socket::INET` (though I think its `new`/`connect`/`listen` methods should take values of the enums defined in `IO`, not just any `Int`), I question whether this would be possible to do for `IO::Socket::Async` because its `connect`/`listen`/`udp`/`bind-udp` methods specifically depend on the socket created using either TCP or UDP; they do not accept taking any socket families, types, or protocols as optional parameters.

**Comment by jnthn** [comment]
> I question whether this would be possible to do for IO::Socket::Async because its connect/listen/udp/bind-udp methods specifically depend on the socket created using either TCP or UDP; they do not accept any socket families, types, or protocols as optional parameters

Sure, but adding an optional family parameter and similar would not break back-compat, nor would treating the existing methods as convenience constructors that delegate to a more general form.

**Comment by Kaiepi** [comment]
> Sure, but adding an optional family parameter and similar would not break back-compat, nor would treating the existing methods as convenience constructors that delegate to a more general form.

True, but another issue with `IO::Socket::INET` and `IO::Socket::Async`'s current design is how they use two completely different APIs, despite `IO::Socket` apparently defining one for sockets in general.

I don't believe `IO::Socket::Async` is special enough not to do the `IO::Socket` role. Creating, connecting, and binding on async sockets with MoarVM aren't async operations with libuv, and neither is listening, but it being one in Raku prevents it from being possible to parameterize `IO::Socket` with what type its socket ops should return. If it instead filled out something like a `connections` `Supply` attribute on the `IO::Socket::Async` using the callback it passes to the async listen op now, this would allow for the two classes to have a consistent API that people would have the option of using for their own socket classes with `IO::Socket`, rather than two entirely different ones. This would make it a lot easier to learn how to deal with networking in general in Raku, and `IO::Socket::INET` could then become a class providing a low-level sockets API, while `IO::Socket::Async` would become a class providing a high level abstraction over the sockets API that would be more suitable to use in most cases.

**Comment by Kaiepi** [comment]
I feel the redesign I was arguing for is pretty drastic and no longer think it'd be something worth pursuing. There is one breaking change to `IO::Socket::INET` that I'm considering that's relevant at the point in the grant work I'm at now though, but I'll make a separate issue for that.
