### ISSUE TITLE
Add Dict/Tuple to the core

### ISSUE THREAD

**Issue by vrurg** [Raku/problem-solving#135]
Opening this as a followup to #99 which was basically resolved in its initial meaning.

We currently have `List` and `Map` which are preserving containers. But there is demand for value types too.

**Comment by vrurg** [comment]
For this reason I'd like to propose adding `Tuple` and `Dict` types into the core which would be deconting their values.

**Comment by vrurg** [comment]
@lizmat you might be interested in this.

**Comment by duncand** [comment]
I support this proposal in principle.  There should be a value-type version of every useful generic collection type.

**Comment by lizmat** [comment]
What can I say: https://modules.raku.org/dist/Tuple:cpan:ELIZABETH/lib/Tuple.pm6

**Comment by vrurg** [comment]
@lizmat I know and propose to move it into the core. `Dict`, as [I noted once](https://github.com/perl6/problem-solving/issues/99#issuecomment-532467970) is just 8 lines of code now.

**Comment by lizmat** [comment]
PR for adding support for `Dict` added with https://github.com/rakudo/rakudo/pull/3331

**Comment by lizmat** [comment]
Following the discussion at https://colabti.org/irclogger/irclogger_log/raku-dev?date=2019-11-29#l499 

We *need* value types for `Associative` and `Positional` roles.  We need these so that they can be used in `QuantHash`es and object hashes.  I do **not** care what they are called.

**Comment by vrurg** [comment]
So, shall we find out the new names? I'd be fine with `Value*`. But considering the existing zoo of datatypes, don't see how this would help without massive renaming of all of them. Which we apperently can't afford.

**Comment by lizmat** [comment]
Related question that I realized the other day: should the `ValueMap` type act as a normal hash, or as an object hash.  In other words, should `ValueMap` be parameterizable?  If so, then maybe we should also allow `Map` to be parameterizable (which it currently isn't).

All in all, we need to think about this more, and how we're going to migrate to any new structure in the future.

**Comment by vrurg** [comment]
Your note left me buffled... This is a situation of 50/50. For sure, `ValueMap` must behave the same as `Map`. But wether it worth having `Map` parameterizeable...

Let's see what we have of cons here:

1. Backward compatibility. Big problem, but its hard to estimate its real scale without running against Blin. At least, quick look through spectests didn't reveal any specific test for the current state of the things.
1. Performance? Perhaps not really.

Pros:

1. Unification. A user tend to consider `Map` as a read-only `Hash` and thus identical behavior would definitely be welcomed.
1. Opening a whole new set of use cases for `Map`s.

My propensity to unification (_similar behaves similarly_) says in favor of parameterizing `Map`.

**Comment by vrurg** [comment]
In retrospection I must admit that, while still considering a `Map`-like parameterizable data type useful, the idea of parameterizing `Map` itself doesn't appeal to me anymore. It would serve us better as a rather simplistic base class for anything more complicated.

If nobody objects to `ValueMap` and `ValueList` anymore I'm about to add a resolution document on this topic which would eventually open the road for adding `Value*` types to the core. BTW, as long as there would be no backward compatibility issues, I think they can be "back-ported" to 6.c.

**Comment by lizmat** [comment]
I'm closing this issue in favour of one I'll be writing in the coming weeks with a more thorough proposal.

**Comment by vrurg** [comment]
Should I close the resolution PR then?

**Comment by vrurg** [comment]
Oh, got the answer in the PR itself.
