### ISSUE TITLE
Visibility of dynamic symbols in async blocks

### ISSUE THREAD

**Issue by vrurg** [Raku/problem-solving#151]
The following code currently just doesn't work on Rakudo 2019.11:

```perl6
sub foo($c, $p, $rp) {
    react {
        note "FOO1 in react: ", $*FOO1 // "*doesn't exist*";
        note "FOO2 in react: ", $*FOO2 // "*doesn't exist*";
        $rp.keep(True);
        whenever $c {
            note "FOO1 in whenever channel: ", $*FOO1 // "*doesn't exist*";
            note "FOO2 in whenever channel: ", $*FOO2 // "*doesn't exist*";
            $p.keep(True);
            done;
        }
        whenever Supply.from-list: ^1 {
            note "FOO1 in whenever from-list: ", $*FOO1 // "*doesn't exist";
            note "FOO2 in whenever from-list: ", $*FOO2 // "*doesn't exist";
        }
    }
}
sub bar(|c) {
    my $*FOO1 = 1;
    start foo(|c);
}

sub baz($c, $p) {
    my $*FOO2 = 3;
    $c.send: 1;
}

my $c = Channel.new;
my $p = Promise.new;
my $rp = Promise.new;
bar($c, $p, $rp);
await $rp;

baz($c, $p);
await $p;
```

rakudo/rakudo#3272 does have a fix for `start` by checking for `Promise`-wrapped code and that's a simple one. The question remains as to how do we handle `react`/`whenever`/`supply` blocks? What symbols are visible to each of the blocks in the sample?

**Comment by vrurg** [comment]
My experimental fix implements the following approach which I personally consider to be the right way to do things, though not without few doubts. The doubts are coming from [a section 'Multiple callers' in continuations paper](https://github.com/perl6/nqp/blob/master/docs/continuations.pod#multiple-callers).

Here is how I consider things:

### `react`

Solemnly belongs to the dynamic scope of `foo`. Thus, is does see `$*FOO1`, but not `$*FOO2`.

### `whenever`

As being a co-routine kind of call, it belongs to the dynamic scope of it's source. In the example both blocks belong to different scopes:

- `Supply.from-list` belongs to `foo` dynamic scope because it is executed in the scope of `react` block. Thus is sees `$*FOO1`
- `Channel` belongs to `baz` dynamic scope. `$*FOO2` is visible then.

But, considering the above mentioned section from continuations documentation, `whenever`s are also part of their static caller scope. From this point of view, the first, `Channel`, one must have access to `$*FOO1`. But that doesn't seem right to me.

**Comment by vrurg** [comment]
### `supply` 

I didn't consider `supply` blocks well enough yet. No proposal on this part yet.

**Comment by jnthn** [comment]
Providing access to the dynamic scope of the place a `start` block was started makes some amount of sense - even if I rather dislike it from a performance perspective - because it can ease refactoring of code to run asynchronously. It's probably just about worth it on balance. However, it is still a surprise that it is not a transitive property (a `start` in a `start` does not see the dynamics of that the outer `start` sees), and making it be one would lead to certain patterns resulting in memory leaks, so we probably won't do that.

I'm not convinced that any magic around dynamic variables is warranted for the `supply`, `react`, and `whenever` constructs. I've probably written as much using these constructs as anyone had, and I've never wanted it to try and carry along dynamic variables from the place where the `supply` or `react` block appeared. I can kind of see it perhaps having a use for `react` blocks - which have side-effects - though certainly not `supply` ones. Further, the performance consequences would be significant, and I fear it'd give a risk of new paths to memory leaks also.

**Comment by jnthn** [comment]
> I fear it'd give a risk of new paths to memory leaks also

And to add: we have had serious leaks relating to `Supply` stuff in the past when contexts were accidentally closed over and retained.

**Comment by vrurg** [comment]
Regarding the transitivity of `start`, with my fix it is transitive:

```perl6
sub foo {
    start {
        await start {
            note $*FOO;
        }
    }
}
my $*FOO = "fii";
await foo; # fii
```

Perhaps it worth noting that it is only supported for `Promise::start` based on already existing `$*PROMISE` and `Promise`'s `$!dynamic_context`. Threads created with low-level are still not retaining their "outer" dynamic scope and that's I consider correct (it's low-level, after all).

Playing a bit with `supply` revealed that `whenever` within it would require additional work to provide same behavior as of that of `react` block.

With regard to the performance, the additional penalty would come from the fact that `&DYNAMIC`  have to lookup through longer call stack chain. But since dynamics are costly anyway and this is a known fact, perhaps it's not that bad.

Don't know which way would it cause memory leaks, to my understanding, as soon as any async block is over and GC'ed, the contexts it keeps reference to should be released and collected too (considering their are released elsewhere). But no doubt, the overall memory footprint will increase and, to be fair, I overlooked this aspect of the matter. Perhaps this makes a good sense to drop the idea altogether.

So, what would be the verdict:

1. Drop it altogether, both `react/supply/whenever` and `start`.
2. Only `start` would preserve the dynamic scope
3. `react` and `start` retain their scopes
4. Implelent the proposal in full.

I consider 3 the worst option of all as it would be really confusing as to why react is the only one. 2 and 4 are my favorites.

**Comment by jnthn** [comment]
> With regard to the performance, the additional penalty would come from the fact that &DYNAMIC have to lookup through longer call stack chain.

No, the problem is that *every single use of `nqp::ctx` is fantastically awful*.

**Comment by vrurg** [comment]
> > With regard to the performance, the additional penalty would come from the fact that &DYNAMIC have to lookup through longer call stack chain.
> 
> No, the problem is that _every single use of `nqp::ctx` is fantastically awful_.

`&DYNAMIC` doesn't use `nqp::ctx` though I suspect that `nqp::getlexreldyn` it relies upon isn't really better in this respect. If I'm right, then support for `start` is better be dropped too as `&DYNAMIC` has to lookup for `$*PROMISE` alongside with looking up for the requisted symbol.

**Comment by jnthn** [comment]
> Don't know which way would it cause memory leaks

Consider something of the structure:

```
sub ticker($interval, &callback) {
    start {
        await Promise.in($interval);
        callback();
        ticker($interval, &callback);
    }
}
```

If that were to let us reach back through the full chain to see any dynamics they introduced *and* those in view at the point of the original start, then we build up an infinitely long chain of remembered contexts.

**Comment by jnthn** [comment]
> I suspect that nqp::getlexreldyn it relies upon isn't really better in this respect

The `rel` part means "relative to a context", so one must have been taken somewhere. To be clear: I don't worry about the cost of dynamic lookups. I worry about the cost we inflict on everything else.

**Comment by vrurg** [comment]
> ```
> sub ticker($interval, &callback) {
>     start {
>         await Promise.in($interval);
>         callback();
>         ticker($interval, &callback);
>     }
> }
> ```
> 
> If that were to let us reach back through the full chain to see any dynamics they introduced _and_ those in view at the point of the original start, then we build up an infinitely long chain of remembered contexts.

I have some bad news for you: this is already a memory leak. `Promise` preserves it's context in `$!dynamic_context` prior to actually starting a thread and that is lately available via `$*PROMISE`. So, the example will work the way you described it.

> The `rel` part means "relative to a context", so one must have been taken somewhere. 

This is clear. I just consider a possibility that this was optimized somehow as I'm not really familiar with moar internals.

> To be clear: I don't worry about the cost of dynamic lookups. I worry about the cost we inflict on everything else.

Still, this part not really clear to me. Since I know about the cost of using dynamics, I usually avoid using them in loops or any other repetitive code. Thus, I'd be less affected by worsening performance if it takes place. Just can't think of other implications right now.

BTW, I'm not defending the proposal. Just trying to consider the issue from different points of view and might be acting as a devil's advocate. :) I do consider this functionality useful, but don't want pay too much for it.

**Comment by vrurg** [comment]
The issue with `start` could be solved by having two distinct ways to start a thread. On the level of `Promise::start` method this could be an additional adverb. Something `:with-ctx` or whatever better name it is given. The default would be not to preserve the context.

On the syntax level it could be an additional statement:

```
my $*FOO = 42;
start { say $*FOO }; # Error for the reason of backcompat with the current implementation
split { # Bad name, but nothing better comes to mind for now
    say $*FOO; # 42
}
```

Or it could be a statement prefix:

```
context start {
    say $*FOO; # 42
}
context react {
    ...
}
```

The prefix would reduce the risk of unintentional use thus reducing the risk of memory leaks.

**Comment by niner** [comment]
On Sonntag, 19. Jänner 2020 02:13:29 CET Vadim Belman wrote:
> But since dynamics are costly anyway and this is a known fact, perhaps it's 
> not that bad.

I'd much rather see us improve performance of dynamics instead of giving up on 
them and making them even worse. Even if the user is aware of our performance 
issues there and working around them, you can't avoid them in all situations. 
There's e.g. $*SCHEDULER which you can't get around. The IO system uses 
$*SPEC. Compilation speed is also heavily affected.

**Comment by vrurg** [comment]
Ok, the sum of arguments is undoubtedly works against the feature.

The only question remains: does it make sense to remove `$!dynamic_context` from `Promise`? I never seen it used in the wild, neither it is utilized in the core. Yet, it takes memory and CPU to be populated with `Promise` caller context.
