### ISSUE TITLE
Routine doc pages need front matter

### ISSUE THREAD

**Issue by treyharris** [Raku/problem-solving#155]
# The problem

Newbies reasonably look to the auto-generated _/routine/…_  pages as a source for learning about a routine, when the docs are currently tooled for them to serve as a reference only. But there’s no clear place for such routine-specific learning material. We should fix this.

## Details
I’ve noticed recently that a lot of traffic from confused newbies¹  both in Raku/doc issues and on the _perl6-users@_ list can be attributed to the newbies’ using the auto-generated _/routine/..._ pages as an entry point for understanding the _Gestalt_ of a routine.

They (naturally, I think) treat the page like they might _perldoc perlfunc_ and read the first definition with seemingly relevant text, even if it’s a snippet from the wrong module. This results in cases like [this perl6-users post](https://www.nntp.perl.org/group/perl.perl6.users/2020/01/msg7865.html), where the user read https://docs.raku.org/routine/get and, based mostly on the documentation of `IO::CatHandle.get` they read at the top of the page, made a lot of incorrect assumptions.

—
_¹ I use “newbies” in a non-derogatory and inclusive sense: it encompasses folks new to the language, folks returning to a working language after having fiddled with older prototypes, and even longtime Raku programmers who are new to particular core functionality._

### Assessment
The _/routine/..._ pages are wonderful as reference for a multiple-dispatch language like Raku, but they are currently really only useful as reference, because they’re automatically assembled in lexicographic order from snippets of every other doc naming each routine.

So we have a bit of an issue. We can reasonably expect others to stumble across routine/ pages. If that’s the entry point to a routine as a matter of reference, that’s fine. But if it’s the entry point as a matter of learning, it’s not good. The first thing you see is the text pulled from IO::CatHandle’s docs, because that’s what comes first lexicographically. But IO::CatHandle’s `get` isn’t the most important one.

So if there’s a need to put some information relating to all variants of a given routine (whether sub, method, or other)—such as “if you landed on this just looking for how to read a line of input, you’re in the wrong place; go look at $link instead”—we have a few options, none good:

1. We can put this info into the docs of the module that is currently first, so it will be first in the assembled routine/ page. But this is brittle (a new or existing module earlier in the alphabet might add the routine some time in the future, and this info will then be second, not first). It would make the canonical document less useful by diluting it with extraneous info. And docs for modules early in the alphabet with many functional siblings (like IO::CatHandle) will suffer especially by having very similar routine-page-oriented info strewn throughout.
2. We can put this info into the routine’s docs of _every_ module. Officially, that’s what we’re supposed to do right now—but for “half a sentence or so” of reduplicated info. A full code example or description of how the routine compares to other routines is too much. It would naturally result in newbies landing on a routine page and, seeing four code examples on one page comparing `lines` to `get`, and then scrolling back and forth trying to figure out how they differ—when the answer is they don’t.
3. We can deal with the issue in one of the intended entry pages. You’ll find that this issue is discussed in the Traps to Avoid and in the Perl 5-to-Raku pages. But we don’t link out to those from the canonical docs—pedagogical material should refer to reference material, not the other way around.
4. We can use linking more heavily, including from reference pages to tutorial pages, to nudge readers to the correct place.

None of these seem like good solutions.

## Suggestions

- **Add routine header files**
  Here, the POD in a new kind of file (e.g., _doc/Routine/get.pod6_) will be prepended to the auto-generated content for routine pages. Here, a discussion of the _Gestalt_ of the routine, references to related routines, etc. could be added and will appear before whatever definition happens to come first lexicographically.
  I think it would be reasonable to relax the guideline against reference materials linking to tutorials for these header pages.
- **Order routine file generation by type hierarchy first**
  For instance, https://docs.raku.org/routine/get should have IO::Handle first.
  It isn’t clear to me whether depth-first or breadth-first makes more sense. From a reading top-to-bottom POV, the depth-first order
  1. (IO::Handle) routine get
  2. (IO::CatHandle) method get
  3. (IO::Socket) routine get
  4. (IO::Socket::INET) method get

would make more sense than the breadth-first

  1. (IO::Handle) routine get
  2. (IO::Socket) routine get
  3. (IO::CatHandle) method get
  4. (IO::Socket::INET) method get
  but the first will fail the "most important stuff first" criterion.

### Desiderata

Some unrelated routines may have the same name; some operators definitely have different functions for different types. Entirely different, like `e` meaning either Euler’s number, or meaning file existence. It seems acceptable (assuming routine header files) to simply discuss the two uses.

But we might want to be able to split routine pages with a disambiguation page, such that https://docs.raku.org/routine/e would say, "do you mean <https://docs.raku.org/routine/e_(number)>, or <https://docs.raku.org/routine/e_(test)>?" — perhaps with a list of signatures and links auto-generated as well.

Another example is https://docs.raku.org/routine/from, which has a CompUnit meaning and a match meaning.

Also, there are several cases of exception method name conflict, both between exception types and often where a payload field name overlaps the name of a constructor (that might be used to create the thing the payload field would contain).

So overall, a way to split routine pages so that homographic routines with multiple semantics can have a page for each broad semantic use would be useful, but such tooling needn't be a blocker on simply adding routine header POD.

**Comment by JJ** [comment]
I almost totally agree with this issue. However, any issue that involves writing a lot of stuff can be dismissed or added to the list of issues in the docs repo, it won't make a big difference; also, in this case, it will need changing the API to collate those headers along with the method info. Doing something on the API that generates the pages would probably be more reasonable, time-wise.

But the only such measure I can think of is using hierarchical order in those pages, instead of lexicographical order. That way, you will get the method for Any or Mu generally, or at any rate something that's deep in the hierarchy and where we could probably tip our hand and link to references. Still would need something to do to improve those first references, but at least there would be something to work on.

**Comment by treyharris** [comment]
On Wed, Jan 29, 2020 at 01:28 Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> I almost totally agree with this issue. However, any issue that involves
> writing a lot of stuff can be dismissed or added to the list of issues in
> the docs repo, it won't make a big difference; also, in this case, it will
> need changing the API to collate those headers along with the method info.
> Doing something on the API that generates the pages would probably be more
> reasonable, time-wise.
>
I have thousands of words—paragraphs of content and code examples I’ve
written—for exactly this purpose, but have found no place in the docs to
put them. I wrote this proposal because I’m getting tired of explaining
routines but not being able to put my explanation in the docs. Because
they’re too small for a document of their own, but far too large to
reduplicate in every single class’s routine POD.

The problem here is not marshalling people to write things—at worse we have
no more information than we did before, as a null or nonexistent header
should just devolve into the same auto-generated page we have now. The
problem is having somewhere to put them where they can be read.

But the only such measure I can think of is using hierarchical order in
> those pages, instead of lexicographical order. That way, you will get the
> method for Any or Mu generally, or at any rate something that's deep in the
> hierarchy and where we could probably tip our hand and link to references.
> Still would need something to do to improve those first references, but at
> least there would be something to work on.
>

**Comment by JJ** [comment]
El mié., 29 ene. 2020 a las 15:43, Trey Harris (<notifications@github.com>)
escribió:

> On Wed, Jan 29, 2020 at 01:28 Juan Julián Merelo Guervós <
> notifications@github.com> wrote:
>
> > I almost totally agree with this issue. However, any issue that involves
> > writing a lot of stuff can be dismissed or added to the list of issues in
> > the docs repo, it won't make a big difference; also, in this case, it
> will
> > need changing the API to collate those headers along with the method
> info.
> > Doing something on the API that generates the pages would probably be
> more
> > reasonable, time-wise.
> >
> I have thousands of words—paragraphs of content and code examples I’ve
> written—for exactly this purpose, but have found no place in the docs to
> put them. I wrote this proposal because I’m getting tired of explaining
> routines but not being able to put my explanation in the docs. Because
> they’re too small for a document of their own, but far too large to
> reduplicate in every single class’s routine POD.
>
> The problem here is not marshalling people to write things—at worse we have
> no more information than we did before, as a null or nonexistent header
> should just devolve into the same auto-generated page we have now. The
> problem is having somewhere to put them where they can be read.
>

As I said, I'm not against this per se. Besides, it would solve the problem
of operators and independent routines, which are right now dispersed here
and there. Also, now we have a good foundation for doing that: Documentable
is not perfect, but at least is an independent module to which we can add
additional specifications like this one if needed.

It will need (relatively) major analysis of that module, and (totally)
major writing of new stuff in the doc. So I guess that's an accept.
The way to proceed in this case is, I guess, to create a PR specifying a
roadmap, so I'll do that and leave both open for discussion.

**Comment by treyharris** [comment]
Great—just wanted to make clear that it wouldn’t be a feature that would be created for disuse. Thanks.

**Comment by JJ** [comment]
El mié., 29 ene. 2020 a las 17:42, Trey Harris (<notifications@github.com>)
escribió:

> Great—just wanted to make clear that it wouldn’t be a feature that would
> be created for disuse. Thanks.
>

I am not thinking about disuse, more about the sheer amount of work it will
involve. There are 1038 routines at last count. But let's see. PR upcoming.
