### ISSUE TITLE
Should $foo ~~ Failure mark Failure in $foo as handled?

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#161]
We can mark `Failure`s as handled by (implicitely) calling the `.Bool` or `.defined` method.

During a debugging session, I found that some places in the test-suite this pattern is being used:

     ok $foo ~~ Failure, ....

to see if a Failure was generated in `$foo`.  And then `.DESTROY` complained that the `Failure` in `$foo` had not been handled.

It feels to me that smartmatching if something is a `Failure`, should *also* mark the `Failure` as handled.  I therefore propose to add to `src/core.c/Failure`:

    multi method ACCEPTS(Failure:U: Failure:D \failure --> True) {
        failure.Bool
    }

This *does* cause some minor spectest fallout, where tests assume that smartmatching with `Failure` does *not* mark the `Failure` as handled.  But this was not the intent of the test, just the result (in my interpretation).

**Comment by jnthn** [comment]
I'm sympathetic to this; if one goes to the trouble of checking if it's a `Failure` then you're almost certainly taking care of the problem anyway - and in case not, and really just wanting the type check, there's `.does(Failure)` as an alternative.

At the same time worried there will be fallout. I'd suggest we blin a branch doing this change, to have more information to work with.

**Comment by lizmat** [comment]
Ok, will add it after the release, and have Alexander run a Blin...

**Comment by jnthn** [comment]
@lizmat Did this happen, and did we get any data?
