### ISSUE TITLE
$*CWD is an IO::Path, IO::Path.CWD is a Str

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#164]
This causes all sorts of unnecessary complexity.

I would like to see either `IO::Path.CWD` turn into an `IO::Path` as well, or `$*CWD` turn into a `Str`.

Doing the latter causes core module installation issues, which seems solvable.  But I have no idea about any ecosystem fallout.

**Comment by vrurg** [comment]
I'd rather vote of the method to return `IO::Path`.

**Comment by niner** [comment]
On Samstag, 22. Februar 2020 02:16:32 CET Vadim Belman wrote:
> I'd rather vote of the method to return `IO::Path`.

Same here. We have a type for representing file system paths. We ought to use 
it :)

**Comment by JJ** [comment]
IO::Path :+1:

**Comment by lizmat** [comment]
It just struck me that I'm looking at this in the wrong way.  Most `IO::Path` objects actually share the same `IO::Spec`, and all files from the same current directory value, share the `IO::Path` (or `Str`) value.

So maybe IO::Path should be a parameterizable class, parameterizable by `IO::Spec` value and by `CWD` value.  @jnthn would that make sense?
