### ISSUE TITLE
qqx not picking up quotes in Windows 7

### ISSUE THREAD

**Issue by ToddAndMargo** [Raku/problem-solving#166]
Dear Raku,

C:\NtUtil>perl6 -v
This is Rakudo Star version 2019.03.1 built on MoarVM version 2019.03
implementing Perl 6.d.

qqx is not handling quoted parameters correctly

This is a good baseline with a file name without a space in it:
```
echo "hi mom" > "test2"
perl6 -e "say qqx { dir test2 };"
 Volume in drive C is DRIVE_C
 Volume Serial Number is 3CDF-1B03
 Directory of C:\NtUtil
02/26/2020  15:24                11 test2
               1 File(s)             11 bytes
               0 Dir(s)  13,269,639,168 bytes free
```

Here is a file name with a space in it:
```
echo "hi mom" > "test 1"
perl6 -e "say qqx { dir 'test 1' };"
File Not Found
 Volume in drive C is DRIVE_C
 Volume Serial Number is 3CDF-1B03
 Directory of C:\NtUtil
 Directory of C:\NtUtil

perl6 -e "say qqx { dir \"test 1\" };"
The system cannot find the file specified.

perl6 -e "say qqx { dir 'test2' };"  # note this works without the quotes
File Not Found
 Volume in drive C is DRIVE_C
 Volume Serial Number is 3CDF-1B03
 Directory of C:\NtUtil
```

**Comment by JJ** [comment]
Sorry, Todd, not the place for this. This would probably go better in StackOverflow or in the mailing list. Also, I don't think it's nothing to do with the (already out of *extended* support) Windows version.

**Comment by ToddAndMargo** [comment]
JJ.  At what point do enough folks on the mailing list have reproduce this issue before it gets past you?

**Comment by JJ** [comment]
I'm answering this question in StackOverflow, which is the place for this, that or the mailing list. This repository has as a tagline:
> 🦋 Problem Solving, a repo for handling problems that require review, deliberation and possibly debate
That's mainly new additions to the language or the general ecosystem. It's *not* the place to solve *your* problems. I have [answered your question here](https://stackoverflow.com/questions/60425787/raku-what-is-the-syntax-for-shell-calls-with-spaces) so please don't generate any more noise in this repository.

**Comment by ToddAndMargo** [comment]
Hi JJ,  Sorry for the noise, but you DID NOT answer the question over on stack.  You gave examples of how to syntax out "echo" but specifically DID NOT address the issue I reported.  You have to specifically address the code I presented.  Show what I and others did wrong, or accept the bug report.

By the way, it reproduces in Windows 10-1909

**Comment by niner** [comment]
@ToddAndMargo you might be reporting a real bug, but this is the wrong repository for it.The problem-solving repo is **not** about bugs. It's about discussing possible changes to the language where the proper path is not clear.

**Comment by ToddAndMargo** [comment]
Hi Niner, Is there a way you can forward the bug to the correct place?  If not, would you give me a link?   -T

**Comment by patrickbkr** [comment]
@ToddAndMargo <https://github.com/rakudo/rakudo/issues>

**Comment by ToddAndMargo** [comment]
Hi Patrick,  Thank you for the link. I reopened the issue over on
qqx, shell not operating quotes properly
https://github.com/rakudo/rakudo/issues/3518
-T

**Comment by ToddAndMargo** [comment]
https://github.com/Raku/problem-solving/issues/20

**Comment by patrickbkr** [comment]
@ToddAndMargo 
The problem-solving issue tracker is for design discussions. So if there is an architectural problem where possible solutions need to be discussed  then problem-solving is the right place.

The Rakudo issue tracker is for bug reports. Something is broken - report the bug there.

So the bug you reported is correctly reported over at rakudo/rakudo#3518.
The problem-solving ticket #20 is not a bug report. It's a question about API design.
