### ISSUE TITLE
New public interfaces are often added without any chance for general consensus

### ISSUE THREAD

**Issue by ugexe** [Raku/problem-solving#169]
Should there be some consensus when new public interfaces are exposed? Or at least a PR period with some measure of time when a consensus could be reached without immediately pushing to master and starting the clock to revert before the next release?

**Comment by lizmat** [comment]
Could you give an example?

**Comment by ugexe** [comment]
Someone comes up with a change. They submit a PR and await for people to give their input regarding naming, security, design, etc. If it gets warnocked then use your best judgement with regards to merging.

**Comment by lizmat** [comment]
This is how I've been treating development of Raku for most of the time I have contributed.

If people feel strongly about something that gets added, they let themselves be known, both for and against it, in my experience.

I would welcome a more structured approach to this, but also realize that the core team is small and mostly overworked.

**Comment by ugexe** [comment]
I understand this. However, for exposing public interfaces specifically (something that shouldn't happen often anyway) I think we it might be wise to take on the cost of the additional structure.

**Comment by lizmat** [comment]
See also discussion at https://github.com/rakudo/rakudo/commit/dceef85f3b1a599eda2956ce1f4cebda3ee54723

**Comment by lizmat** [comment]
https://github.com/rakudo/rakudo/commit/1d57d17da0 and https://github.com/rakudo/rakudo/commit/0c36feb07d will omit implementation detail entities unless forced with `:implementation-detail` parameter.

Questions:
- did I miss an avenue of introspection
- should the named parameters be called something else?

**Comment by lizmat** [comment]
Closing because I think this issue is basically solved now that these types of things are done by PR's nowadays.
