### ISSUE TITLE
Redesign Exceptions for subclassing

### ISSUE THREAD

**Issue by JJ** [Raku/problem-solving#173]
Except for [the `Exception` class](https://docs.raku.org/type/Exception), the rest do not seem to have an easy public interface for subclassing (or, for that matter, composing).

For instance, the [`X::Obsolete` class](https://docs.raku.org/type/X::Obsolete) might be subclassable in a particular class hierarchy, with defaults for the `where` attribute, and maybe other kind of defaults. Problem is, you can't do it: the only way to work with it is to include it as an attribute, because there are no setters for its attributes (so you can't assign values in a TWEAK phaser), and of course you can't do it in the BUILD phaser. Eventually, it's better to go down one step in the ladder and just create your own Obsolete class with its own interface and attributes, which you can then subclass. 

Same would go for X::FYI or even X::TypeCheck and X::AdHoc.

In general, the issue seems to be extensive to all the X class hierarchy: classes seem mostly designed for internal use in Rakudo; the fact that its semantics might be useful for end users is mostly a side effect. But a well defined set of base exceptions would really help to design solid, interoperable class hierarchies; there's some added value in being able to catch a "X::TypeCheck" exception independently of the module that's thrown it.

## Sugestions

Decide on a small bunch of classes (like TypeCheck, AdHoc, NYI and Obsolete) and make them roles so that they can be composable. You will be able to catch any exception of that type as long as it composes the base role.

**Comment by jnthn** [comment]
> For instance, the X::Obsolete class 

For reference, included here, so we can see it's not doing any internal trickery at all:

```
my class X::Obsolete does X::Comp {
    has $.old;
    has $.replacement; # can't call it $.new, collides with constructor
    has $.when = 'in Raku';
    method message() { "Unsupported use of $.old; $.when please use $.replacement" }
}
```

> Problem is, you can't do it: the only way to work with it is to include it as an attribute, because there are no setters for its attributes (so you can't assign values in a TWEAK phaser), and of course you can't do it in the BUILD phaser

Dunno what "phaser" is about; they're submethods. But still, the attributes are set as usual: at construction time, by being passed into the constructor. You can override the `new` if you really want to default them differently.

> Eventually, it's better to go down one step in the ladder and just create your own Obsolete class with its own interface and attributes, which you can then subclass.

I don't see what would be different; your own subclass still won't get any different access to the parent class attributes, unless it makes the `is rw`, which seems highly undesirable.

**Comment by jnthn** [comment]
Also:

> TypeCheck

This one has multiple successful examples of subclassing in the core itself.

> AdHoc

Probably shouldn't be subclassed given it indicates a lack of typed exception.

> NYI

There's also examples of this being subclassed in core.

**Comment by JJ** [comment]
The thing is that X::Comp is designed to be composed. It seems to be the only one done with that in mind. Composing makes everything easier.

I'm using as examples what's there; they are probably not good examples. On the other hand, there are a good amount of roles (including X::Comp) in the class hierarchy; they're there for a good reason, but most of them are useful for internal reasons (we might co-opt X::Syntax for something, but still it might be better to have some other base class). Even more so, all of these roles subclass Exception, they don't subclass anything else because it's not so straightforward...

Also, in the cases they're being subclassed (which I don't say was impossible) they're using available getters or setters. I see that in most cases the attributes are public, which is a good idea. I might have bumped into the only one that's got only private attributes... 

Anyway, you have a point, so I guess it's better to just close this. Thanks!
