### ISSUE TITLE
Attributes could use more support for reflection

### ISSUE THREAD

**Issue by Kaiepi** [Raku/problem-solving#174]
A feature being added to `Trait::Traced` once the next compiler release gets made is tracing for attribute and variable declarations. There are a couple of problems with attribute introspection it needs to work around though, since it tries to output declarations as they were written:

- `has $!foo`, `has $foo`, and `has $.foo` all get their name stringified as `$!foo` by `Attribute.Str` and `Attribute.gist`. As far as I know, there's no way to differentiate between `has $!foo` and `has $foo` at runtime, so this means having an fragile hack like this in `&trait_mod:<is>` to determine how an attribute is twigiled:
```perl6
my Str:D $name = $attribute.name;
if $attribute.has_accessor {
    $name .= subst: '!', '.';
} elsif $*W.?cur_lexpad.symbol: my Str:D $symbol = $name.subst: '!', '' {
    $name = $symbol;
}
```
- As far as I know, there's no way to differentiate between `has $!foo` and `has Mu $!foo`. These both get stringified as `Mu $!foo` by `Attribute.gist`.

It would be nice if `Trait::Traced` could simply use `Attribute.gist` or `Attribute.Str` (or perhaps a new `Attribute.raku`) to output attribute declarations, but I don't feel support for attribute introspection as it stands now is good enough to allow this.

**Comment by Kaiepi** [comment]
I propose adding the following methods:

- `method is_lexical(Attribute:D: --> Bool:D)`

Returns whether or not the attribute was declared to have a lexical symbol (`True` for `has $foo`, `False` for `has $!foo` and `has $.foo`).

- `method is_typed(Attribute:D: --> Bool:D)`

Returns whether or not the attribute was declared with an explicit type.

- `method sigil(Attribute:D: --> Str:D)`

Returns the sigil the attribute was declared to have.

- `method twigil(Attribute:D: --> Str:D)`

Returns the twigil the attribute was declared to have (`'!'`, `'.'`, or `''`).

- `method usage-name(Attribute:D: --> Str:D)`

Like `Parameter.usage-name`, returns the attribute's name minus the sigil and twigil it has.

- `multi method raku(Attribute:D: --> Str:D)`

This would behave similarly to `Parameter.raku` WRT how to stringify the attribute: it would be prefixed with `'has '`, followed by a type (if any), followed by the attribute name as it was written.

This is a similar issue to https://github.com/Raku/problem-solving/issues/149, so I feel a similar solution would be in order: attribute flags. This would save some memory while allowing more bools for attributes to be added with little cost. The following flags would replace a bunch of old attributes of `Attribute`:

- `ATTR_IS_BUILT`
- `ATTR_IS_BOUND`
- `ATTR_HAS_ACCESSOR`
- `ATTR_IS_RW`
- `ATTR_IS_RO`
- `ATTR_IS_REQUIRED`
- `ATTR_IS_INLINED`
- `ATTR_IS_BOX_TARGET`
- `ATTR_IS_POSITIONAL_DELEGATE`
- `ATTR_IS_ASSOCIATIVE_DELEGATE`

With the following being new flags:

- `ATTR_IS_TYPED`
- `ATTR_IS_LEXICAL`

This should make the new methods possible to implement.

**Comment by b2gills** [comment]
I don't think this would be worth doing, at least at this time. Jnthn has been implementing a RakuAST, and that may be a better way to implement such things.

[Realizing Raku Macros](https://www.jnthn.net/papers/2020-gpw-realizing-raku-macros.mp4)

**Comment by Kaiepi** [comment]
Fair.

**Comment by jnthn** [comment]
Yes, I think the design principle from now on as to whether information goes into a meta-object or not will be: does something in the standard language need this at runtime? If not, one obtains it through the AST (and language extensions that do need the info at runtime too are free to do whatever mixins they wish to preserve it for longer).

I don't really intend that we go back and review existing meta-objects for such cases, unless there's a really big win from doing so. Probably my first target in that case would be regexes having a stringification of the regex attached (`like` in `Test.pm6` can become a `macro`)...

**Comment by jnthn** [comment]
Given it's decided that RakuAST will be the answer for this, I see no reason to leave the problem solving issue open.
