### ISSUE TITLE
Should we allow directories as destinations for IO::Path.copy/move?

### ISSUE THREAD

**Issue by JJ** [Raku/problem-solving#181]
This was a feature that was going to be added [in this PR](https://github.com/rakudo/rakudo/pull/2043). It didn't reach consensus (and now causes a conflict), so it's better to start over and decide if that's what we really want.

Please read through [comments](https://github.com/rakudo/rakudo/pull/2043) for proposed solutions, or propose your own below; read also [the original issue](https://github.com/rakudo/rakudo/issues/1453) that caused the PR for more context.

**Comment by vrurg** [comment]
I think the ecosystem solution is the one to go on with. No reason to waste time on in-core support implementation.

**Comment by jnthn** [comment]
> Should we allow directories as destinations for IO::Path.copy/move?

Given the caveats mentioned in the PR discussion, not without being asked to consider the destination as a directory. Maybe even `move-to-dir` and `copy-to-dir` to spell it out.

> No reason to waste time on in-core support implementation.

Well, one could also argue that we shouldn't waste people's time hunting modules for common I/O requirements. Question is how common this is, but...

> I think the ecosystem solution is the one to go on with.

Well certainly, ecosystem first, which is the same immediate action. I'm open to considering a well-tested implementation going into core in the future, if there's enough demand (e.g. it warrants its inclusion).
