### ISSUE TITLE
Should we make short-id2class accessible?

### ISSUE THREAD

**Issue by JJ** [Raku/problem-solving#189]
Proposed in rakudo/rakudo#757, as indicated by @MadcapJake, it would allow someone to add custom CURs to the short-id registry. Please see discussion there for pros and cons (and add your own here)

**Comment by jnthn** [comment]
I'd like @niner or @ugexe to comment on if this is sensible with regard to the API. If it is exposed, it should not be under that name (using the number "2" in place of the word "to" is tolerable in internals, but not a convention we have anywhere else).

**Comment by jnthn** [comment]
Ah, @niner already *did* in the linked issue, which I should have read first. So the answer is "no we shouldn't", which settles this issue, however I have the impression there's still an underlying issue that could be worthy of a fresh problem solving issue.
