### ISSUE TITLE
.? behavior on signature mismatch: clarification of semantics

### ISSUE THREAD

**Issue by vrurg** [Raku/problem-solving#190]
I'm just moving here Raku/roast#72 case. The following is a quote from the original PR:

--------
How should a .? dispatch be handled when the method exists, but the signature
does not match? The current de facto implementation takes a very literal
interpretation of S12 and checks to see if the method exists. If it does, then
it will fail with an exception related to signature mismatch. If it does not,
then no operation occurs and Nil is returned.

I suggest that for the sake of doing something like this:

```
$object.?one.?two.?three;
```

that it makes more sense to take the signature into account. That is, if method
"one" returns an object of type One with a two method defined like this:

```
class One {
    method two(One:D:) returns Two { ... }
}
```

and Two is similarly defined, should .? dispatch continue or fail? I understand
(from coworkers) that Swift and C# have .? operators that would succeed. In the
case of C# (which I know very little about) can just short-circuit on the first
null it encounters. Perl 6 can actually provide type context for it's null
values though and might provide a valid method to dispatch.

--------------------

**Comment by vrurg** [comment]
This is two options @zostay proposes:

1. We allow .? dispatch to succeed with a Nil in any case where the method
   signature of the call does not match the method signature of the object.
2. We allow .? dispatch to succeed with a Nil only in cases where the method
   signature mismatches on a multi-method. Any regular method would still fail
   with an error on the signature.

My own option is 3:

3. The current implementation does everything right and no change is needed.

The reasoning is in the proclaimed semantics of `.?`: it is supposed to call a method if found. In both cases of single and multi variants the method _does_ exists. Thus, `.?` must call it and must not care about the outcome of the call, including any possible errors.

**Comment by jnthn** [comment]
I've considered this a number of times before, and also about its behavior with regard to multiple dispatch.

Generally in Raku we don't consider parameter binding as part of the dispatch process. Once you have a matching candidate, that's where you going. If the signature fails to bind, that's not a problem with dispatch.

Even in multiple dispatch it's defined as a two-step process (find the best candidate and call it), and there's even syntax (`;;`) for hiding some of the arguments from multiple dispatch process too. For a multi-method dispatch there's thus 3 steps: find the proto, find the candidate, call the candidate.

Today, all of `.?`, `.+`, and `.*` are defined in terms of the first step only. We could potentially consider making them also be about multi candidates too, though it'd need to be at a language version boundary to not break existing code.

**Comment by vrurg** [comment]
I don't think we should ever get beyond one step. Otherwise it'd open a whole new world of hidden errors of the kind 'I have a method for this, why doesn't it work?'. Especially in cases with quirky signatures where it's not easy to spot a problem at the first glance.

On top of it, certain edge cases could make the operator behavior rather convoluted. One coming to mind is when proto signature doesn't match:

```
proto method foo($) {*}
multi method foo(Str $s) { ... }
...

```

Besides, the case doesn't seem to be popular enough to worth investing time into it.

**Comment by vrurg** [comment]
On top of it, we leave `.*` out of the question. But I'm certain it would add to the list of edge cases to be resolved.

The desired behavior of `.?` could easily be emulated when necessary. With `.*` things are in even better shape as `Mu::WALK` is a swiss-army-kinfe replacement which already covers the case of failed invocations:

```
Foo.new.WALK(:name<foo>).quiet.invoke("the answer", 42)
```

**Comment by vrurg** [comment]
Closing as the behavior is anyway specifically specced at https://github.com/Raku/roast/blob/e073870ba112f0cf1a3b60d41ab791fb9ba32772/S12-methods/calling_sets.t#L79

**Comment by jnthn** [comment]
> I don't think we should ever get beyond one step. Otherwise it'd open a whole new world of hidden errors of the kind 'I have a method for this, why doesn't it work?'.

Yeah, that's what I feared too.

Having pondered it a bit more, it seems that while other behaviors *might* be interesting to offer at some point, it's not like the current one is in any sense wrong or not useful, so it'd be strange to take it away and replace it with different semantics. So far as this issue is about the current semantics of `.?`, I think the issue is resolved. however.
