### ISSUE TITLE
Only allow IO::Path.open to create an IO::Handle

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#196]
Currently, you can create an `IO::Handle` with `IO::Handle.new` and thereby set all sorts of attributes.  But then, calling `$handle.open` you can change / add / reset a lot of these attributes, causing a piece of spaghetti code trying to handle all possible cases of defaults / changes, etc.

My proposal is to make calling `IO::Handle.new` an execution error.  The only way to create an `IO::Handle` object, should be by calling `open` on an `IO::Path` object.

    my $handle = $filename.IO.open(:w, :enc<utf16-le>);

instead of allowing something like:

    my $handle = IO::Handle.new(:path($filename), :enc<utf16>, :!chomp).open(:enc<utf8>, :chomp)

**Comment by niner** [comment]
I was pretty confused by our ability to have un-opened handles which I 
discovered only a few days ago. I'm very much in favor of removing this 
feature if the ecosystem permits.
