### ISSUE TITLE
META6.json perl  key

### ISSUE THREAD

**Issue by fooist** [Raku/problem-solving#226]
The “perl” key in META6 is inaccurate.

As a new Raku user, there are still numerous places where the artifacts of Perl6 —> Raku still exist. This one goes from amusing to confusing.

However, changing it would require (that I know of) changes to at least:
- [zef](https://github.com/ugexe/zef/blob/846c5ab92cdf6a788abc23b19ce81979b84d8e4a/lib/Zef/Service/P6CReporter.pm6)
- [META6](https://github.com/jonathanstowe/META6)
- [Raku/doc](https://github.com/Raku/doc)

There could be issues elsewhere ([Raku::Ecosytem](https://github.com/Raku/ecosystem)?).

**Comment by fooist** [comment]
My suggestion is to start with a change to META6 that provides a 2-way alias, then change the docs, then encourage changes wherever they are in other places/packages.

At some point the use of "perl” could be deprecated and eventually removed.

cc: @jonathanstowe

**Comment by jonathanstowe** [comment]
Hi, in the next release of `META6`  the `perl-version` attribute (that holds the `perl` attribute from the `META6.json`) will become deprecated and optional and the `raku` attribute will be added.  At some point soon after that I will add a test for the deprecated attributes in the `Test::Meta` as a warning.  Then after a cycle or two I will make the deprecated attributes a fail in `Test::Meta` and *then* after a further cycle remove the `perl` attribute from the `META6` altogether.  I'd recommend adding *both* to the `META6.json` in the first place, adding aliasing would make the deprecation rather difficult and I'd rather not be adding too much code to `META6` to support a one-off transition.

**Comment by fooist** [comment]
That’s fantastic!
