### ISSUE TITLE
rx:s/ / is considered a null regex

### ISSUE THREAD

**Issue by holli-holzer** [Raku/problem-solving#230]
Observe: 
```
>6e "' ' ~~ rx:s/ /"
===SORRY!=== Error while compiling -e
Null regex not allowed
at -e:1
------> ' ' ~~ rx:s/ <HERE>/
6 -v
This is Rakudo version 2020.05.1 built on MoarVM version 2020.05
implementing Raku 6.d.
```

Since :sigspace is active, / / should not be a "null regex" but a regex consisting of a single chr(32) whitespace.

**Comment by Altai-man** [comment]
This seems like a bug report ticket for [Rakudo](https://github.com/rakudo/rakudo) repository, not something fitting for the problem solving repo.

**Comment by holli-holzer** [comment]
My bad.

**Comment by timo** [comment]
the first whitespace in a sigspace regex is ignored, which is why the regex in this case is considered a null regex

**Comment by timo** [comment]
here's a quote from the documentation:

> Where whitespace in a regex turns into <.ws> depends on what comes before the whitespace. In the above example, whitespace in the beginning of a regex doesn't turn into <.ws>, but whitespace after characters does. In general, the rule is that if a term might match something, whitespace after it will turn into <.ws>.
>
> In addition, if whitespace comes after a term but before a quantifier (+, *, or ?), <.ws> will be matched after every match of the term. So, foo + becomes [ foo <.ws> ]+. On the other hand, whitespace after a quantifier acts as normal significant whitespace; e.g., "foo+ " becomes foo+ <.ws>.

https://docs.raku.org/language/regexes#index-entry-regex_adverb_:sigspace-regex_adverb_:s-Sigspace
