### ISSUE TITLE
Documentation search categories are not standardized

### ISSUE THREAD

**Issue by Altai-man** [Raku/problem-solving#250]
Current documentation metadata contains search items divided into categories.
The problem is that:

- [ ] Existing categories were not designed uniformly from the start;
- [ ] A documentation writer can create a new category simply via metadata, which sometimes interpreted incorrecly by the writer and a nonsense search category is created.

As a result, user sees bogus search categories.

There is a long discussion at https://github.com/Raku/doc/issues/1410 going into all kinds of details.

**Comment by Altai-man** [comment]
Initial proposal:

Settle on a consistent set of categories that will be based on both existing categories (so those can be absorbed into the new set) and prepare safety net measures for cases when humans accidentally create bogus categories (write a test that will fail when encountering an item with category not included into our set).
Eventually, gradually patch the documentation piece by piece to migrate from old categories to new ones.

Current categories:

- [ ] class
- [ ] role
- [ ] enum
- [ ] module
- [ ] Language
- [ ] programs
- [ ] sub
- [ ] prefix
- [ ] listop
- [ ] infix
- [ ] Routine
- [ ] postfix
- [ ] postcircumfix
- [ ] method
- [ ] submethod
- [ ] routine
- [ ] trait
- [ ] term
- [ ] twigil
- [ ] variable
- [ ] syntax
- [ ] regex
- [ ] regex quantifier
- [ ] parameter
- [ ] quote
- [ ] matching adverb
- [ ] regex adverb
- [ ] substitution adverb
- [ ] hyper
- [ ] Phasers
- [ ] Asynchronous Phasers
- [ ] Python
- [ ] constant
- [ ] hash (Basics)
- [ ] rakudoc
- [ ] control flow
- [ ] :sym<>
- [ ] scalar (Basics)
- [ ] statement (Basics)
- [ ] string literal (Basics)
- [ ] TOP
- [ ] topic variable (Basics)
- [ ] variable interpolation (Basics)
- [ ] declarator
- [ ] :cached
- [ ] eager (statement prefix)
- [ ] gather (statement prefix)
- [ ] identifier
- [ ] classes
- [ ] lazy (statement prefix)
- [ ] macros
- [ ] pack
- [ ] react (statement prefix)
- [ ] sink (statement prefix)
- [ ] supply (statement prefix)
- [ ] <sym>
- [ ] ->
- [ ] is default (Variable)
- [ ] try (statement prefix)
- [ ] with orwith without
- [ ] Reference

New categories suggested (old ones that can be dissolved into a category are written in parentheses)

- [ ] Types (class, role, enum) - for Raku types
- [ ] Modules (module) - for Raku std modules
- [ ] Subroutines (sub, Routine, routine) - for Raku subs
- [ ] Methods (method, submethod) - ...
- [ ] Terms (trem) - ...
- [ ] Operators (prefix, listop, infix, postfix, postcircumfix) - ...
- [ ] Adverbs (matching adverb, regex adverb, substitution adverb) - all adverbs
- [ ] Traits (trait, is default (Variable), is) - Raku traits
- [ ] Phasers (Phasers, Asyncronous Phasers) - phasers
- [ ] Syntax (twigil, syntax, quote, <sym>) - various bits of language syntax explained at meta-level
- [ ] Regex (regex, regex quantifier, :sym<>) - everything related to regex
- [ ] Control flow (hyper, control flow, try, with orwith without, supply, sink, react, lazy, gather, eager) - everything related to control flow
- [ ] Syntax (quote, string literal, declarator, identifiers) - Raku syntax bits, quoting, literals, identifiers
- [ ] Variable (variable, constant) - constants. Also stuff like `$=` should really be categorized here, not in `Reference`
- [ ] Reference (scalar, statement, topic variable, variable interpolation, parameter, Reference) - reference to things at meta level
- [ ] Language (pack, Language, macros)
- [ ] Programs - How to debug, run, type
- [ ] Foreign (Python) - for items from other languages, migration guides.

Bogus categories that will be completely removed:

- [ ] hash (Basics)
- [ ] scalar (Basics)
- [ ] statement (Basics)
- [ ] string literal (Basics)
- [ ] TOP
- [ ] topic variable (Basics)
- [ ] variable interpolation (Basics)
- [ ] :cached
- [ ] classes
- [ ] <sym>
- [ ] ->

**Comment by JJ** [comment]
I support that proposal.
