### ISSUE TITLE
Documentation and the ecosystem

### ISSUE THREAD

**Issue by JJ** [Raku/problem-solving#252]
Right now, there's a module called `p6doc` which you can download using zef. However, once downloaded it does not really do anything sensible, other than [producing errors which, in turn, produce confusion](https://github.com/Raku/doc/issues/3750). Those errors can be fixed, but the real issue is that documentation is *not* an installable module. There are a couple of modules in the `lib` directory, mainly helpers for testing the documentation, but that's that. If you want to *actually* have the documentation, you will need to get into the directory `zef` has downloaded it into, install `Documentable`, and run it according to instructions. That's something that you can obviously achieve more easily just cloning the repo, and you will avoid any kind of confusion. Even if you do that, you'll end up with something that's already on the web, easily accessible from anywhere.

**Comment by JJ** [comment]
My solution for this would be to simply remove `p6doc` from the ecosystem. As a developer, there's nothing really useful there since all business logic has moved elsewhere. There's the problem of accessing documentation from the command line, though, which is something we might want to have; but that's moved elsewhere, to `rakudoc`, which can use it's own means to install and access the documentation.
If we want to move in the other direction, to actually make it useful somehow as installed, there's the issue [of actually making documentation available as a CUR repository](https://github.com/Raku/doc/issues/3206) or some other way that can be accessed using `%?RESOURCES` that's a different kettle of fish, however. We might want to do it, but it will need resources and time. It's not incompatible with the first option, so for the time being I would opt for just eliminating it from the ecosystem.

**Comment by JJ** [comment]
Additionally, we should probably change the name to something like Raku::Doc

**Comment by patrickbkr** [comment]
I'm in favour of removing.

**Comment by JJ** [comment]
Alternatively, we could substitute it by a kinda-rakubrew that would download the documentation, Documentable and install it in your system, if you so want...
