### ISSUE TITLE
Subdomain for the Raku Course

### ISSUE THREAD

**Issue by ash** [Raku/problem-solving#257]
I propose to create a subdomain course.raku.org to host the course that I am writing within a TPF grant.

As of today, the first (of 5) part is ready and I am about to make it public in the grant report in the coming days (~ next week?). The course is a set of static files https://github.com/ash/raku-course/tree/master/docs which are hosted as GitHub Pages with a custom domain. Currently, I am using https://course.raku.online, but It would be great if it is a part of raku.org and the URL stays the same after it goes public.

What needs to be done is to add a CNAME record to the DNS:

`course		IN	CNAME	ash.github.io.`

It is fine to give a different name to the 3rd level domain.

**Comment by lizmat** [comment]
course .raku.org feels fine to me.

**Comment by nxadm** [comment]
Isn't course singular not a little authoritative? What if there is another course available later? Maybe a more generic landing page with resources would be useful?

**Comment by lizmat** [comment]
Hmmm...  that would help in the stability of URLs I guess  @ash I assume the landing page would give an overview of the parts of the course, right?  So it could later serve as a more generic landing page?

**Comment by ash** [comment]
The front page currently contains the TOC: https://course.raku.online. When the other parts arrive, I will remove the links to the deepest pages to make the TOC smaller. Not quite sure what you mean by a more generic page.

**Comment by lizmat** [comment]
@ash A more generic page that would also link to other courses?

**Comment by ash** [comment]
It would mess things up. I cannot maintain the lists of other courses or such.

**Comment by nxadm** [comment]
That's pretty much the idea of what I meant: you don't maintain it. A generic page links to your and others courses or resources. It would be different if your course would be *the* "official" book, like [the one of Rust](https://doc.rust-lang.org/book/), maintained by the community.

**Comment by ash** [comment]
How official is the course created within a grant of TPF?

**Comment by nxadm** [comment]
> How much official is the course created within a grant of TPF?

A grant does not something official, but I may be wrong.

> And that generic page already exists: https://raku.org/resources/

That looks like a perfect place to me. Maybe it's something the RSC can look at.

**Comment by ash** [comment]
In any case, it should be a separate domain or a subdomain, as I'd like to avoid adding a prefix to the URLs. Neither I want to unintentionally mislead the user where is the borders of this particular course.

The domain can be linked from https://raku.org/resources/, but as Raku is intended to be a 100-years language, an organisation must keep the domain. 

Or, something like course1.raku.org is also fine.

**Comment by JJ** [comment]
Let's not get bogged down on naming. He's requested course.raku.org, let's give him course.raku.org. When and if there are other courses, we can see what can be done with that.

**Comment by rba** [comment]
I have added the requested `course IN CNAME ash.github.io.`. @ash Please check if you need to change the domain on the github pages side.

While understanding the idea of keeping things on a generic level and being open for the next course/training to find good spot too. Yet this can be rearranged as well when the next shows up.

**Comment by ash** [comment]
@rba it works!

Thanks everyone for quickly reacting to my request!
