### ISSUE TITLE
Independent CI server for Raku modules and infrastructure

### ISSUE THREAD

**Issue by melezhik** [Raku/problem-solving#258]
Problem -  Raku community needs an independent, vendor free CI solition.

Considering a recent Travis CI reducing open source support,  we need a CI solution that enables us persistent and flexible environment for Rakudo development, including Raku modules.

**Comment by melezhik** [comment]
My suggestion is to use [Sparky](https://github.com/melezhik/sparky) CI for that. 

Reasons:

* it's written on Raku
* it's built on Sparrow and has now 200+ plugins included - https://sparrowhub.io
* it's already tested for various cases including RakuDist and RakuPlay

Things to discuss:

* Enable DSN name for Sparky playground http://161.35.142.50/ , something like sparkyci.raku.org for the start
* Think about potential components of Rakudo infrastructure that  due to TravisCI's ceasing of support of such could be switch to Sparky, at least it could be a good test case to see how Sparky itself 
* I am open to support some community Raku modules, just because the server capabilities are limited ( digital ocean basic dropplet ) I can't of course now about all the modules, anyway some examples could be found at the playground 
* Just any constructive feedback is welcome 😄

**Comment by patrickbkr** [comment]
Please do note that there is already a separate project underway to provide a  stable CI platform for the core projects (MoarVM, NQP, Rakudo). [problem-solving#206](https://github.com/Raku/problem-solving/blob/fedec010447e5707cce6320fcb4bd9811dc58f6c/solutions/fallback/commit-and-release-policy.md#improvements-to-our-ci-pipeline) I'm slowly working on implementing that CI orchestrator / bot and applied for a grant to finish that sooner. I'd hate for work to be duplicated, so we should make sure we are not pushing for different solutions to the same problem. My approach does not cover the topic of testing Raku modules at all though, it's exclusively dealing with testing the core projects. What's your opinion how we should proceed?

**Comment by melezhik** [comment]
Hi @patrickbkr , I see. I checked out the link, looks reasonable. I wonder if Sparky could be used as part of the solution you're doing. Maybe we could take about this via irc/email?

**Comment by melezhik** [comment]
Sorry. Can we close this one? I decided to put activity with Sparky on hold due to some ("none technical") reasons. Thanks for consideration.
