### ISSUE TITLE
Method `reverse` on ranges should produce ranges

### ISSUE THREAD

**Issue by vrurg** [Raku/problem-solving#259]
This would rather be a question but might end up in an actual change. The problem is rather simple to formulate: why doesn't `Range::reverse` returns a `Range` with min/max reversed? This should make cases like rakudo/rakudo#3599 and many similar ones more consistent.

**Comment by vrurg** [comment]
The current implementation really makes it hard to explain why `(0..Inf).reverse` behaviour is different from `(Inf..0)` and alikes.

Since the change is rather simple, I gave it a try and apparently it breaks spectests. I only got time to consider only one breakage:

```
    test-iter-opt ^3 .iterator,         (0, 1, 2), 'Range';
    test-iter-opt ^3 .reverse.iterator, (2, 1, 0), 'Range.reverse';
```

So far, I'd make more sense to me if `^3.reverse` behaves the same as `3^..0`, i.e. results in an `Empty`.

Apparently, other breakages are to be considered too before any final conclusions are made. But what's clear right now is that the change of this kind could only be implemented in `6.e`.

**Comment by jnthn** [comment]
> So far, I'd make more sense to me if ^3.reverse behaves the same as 3^..0, i.e. results in an Empty.

To me that feels like wonderfully consistent but also a little bit useless: every reversed non-empty `Range` will become an empty range.

**Comment by jnthn** [comment]
Ah, the other problem is predictability.

```
$ ./rakudo-m -e 'sub f(@x) { @x.reverse }; say f((1,2,3)); say f(1..3)'
(3 2 1)
(3 2 1)
```

This would change under the proposal.

**Comment by vrurg** [comment]
> > So far, I'd make more sense to me if ^3.reverse behaves the same as 3^..0, i.e. results in an Empty.
> 
> To me that feels like wonderfully consistent but also a little bit useless: every reversed non-empty `Range` will become an empty range.

True, useless in most cases. But consistent. :) And considering that current behavior is less than predictable in certain cases, as the original ticket notes, it's easier to explain why `f(1..3)` results in empty list than why `(Inf..0).reverse[^10]` produces a list of `Nil`s.

Though, I think [saloritz' comment](https://github.com/rakudo/rakudo/issues/3599#issuecomment-760619261) worth paying attention too. If `(Inf..0)` is instantly equivalent to `Empty` and not a subject for lazy evaluation, this would also be quite reasonable behavior. Same applies to `NaN` if it's postulated that any range containing it is `Empty`.

**Comment by jnthn** [comment]
> But consistent. :)

There's more than one way to be consistent, the question is which we place more value on. If `reverse` always coerces to a `list` and then reverses that, that's also a consistent and predictable behavior.

**Comment by pmichaud** [comment]
To follow up a bit, "reverse" is pretty well defined to always work on a list.

I think it's worth noting that we defined "reversing a Str" as method "flip" simply to avoid the confusion about what reversing a Str would mean.

Based on that, I think that .reverse should continue to have its List-y interpretation, and if there needs to be a shortcut for re-ordering the endpoints of a Range, explore how that might be done.

Pm

**Comment by vrurg** [comment]
Following @pmichaud note, we may introduce `inverse` method which will do exactly that:

1. Preserve the original type of its invocant.
2. Flip-flop start and end points.
3. For reified positionals it would be equivalent to `reverse`.

The idea is rather fresh, spoken out for consideration purposes. I myself gonna think over it.

**Comment by salortiz** [comment]
Although I am sympathetic to the convenience of Raku types being "closed" in the mathematical sense, usability and composability should be prioritized. So I think the best option is to formalize and document that raku's `Range` is limited to be "ascending".

This formalization only implies that:

Early fail if min > max. And in this case I think returning `Empty` is a better option than `Failure`. (The possibility of  a `warn` can studied). 

`Range.reverse` should not be expected to produce a `Range`, today it produces Seq but could produce other types of Sequence.

I.e. More complex ranges, (descending, fractional increments/decrements, etc.) should be defined in other Types.

**Comment by vrurg** [comment]
> I.e. More complex ranges, (descending, fractional increments/decrements, etc.) should be defined in other Types.

I think you meant sequences here, not ranges.

**Comment by salortiz** [comment]
@vrurg. I wrote "ranges" in lowercase to differentiate from raku`s `Range`, but yes, I meant other types.

Of those others, some may inherit of `Seq`, some of a more generic type with a `start` and `end` attributes. (`Seq does Sequence` that now `does PositionalBindFailover`, so may be don' t accept fractional increments).
Those will be material for other problem-solving issue.

My intention for this one is to have a useful and predictable `Range`, and a `Range` that can not be iterated seems to me of little use.

**Comment by vrurg** [comment]
On the purpose of not littering problem-solving with issues unlikely to be solved any time soon, I'm closing this one.
