### ISSUE TITLE
Provide a way to explicitly set arg0 when calling a program

### ISSUE THREAD

**Issue by patrickbkr** [Raku/problem-solving#260]
In Raku there currently is not way to set arg0 explicitly when calling a process. This procedure is sometimes referred to as "lying about arg0". It can be helpful in rare circumstances. The most obvious one being calling programs that mimic different programs and inspect their arg0 to determine which they should act (e.g. busybox).

**Comment by patrickbkr** [comment]
One rarely needs to set arg0, so a solution should not interfere with the default use of the calling API. Also staying backwards compatible is desirable.

I propose we add a new argument to different process calling functions and methods named `arg0`. If unset arg0 will be set to the program being called (unchanged from current behavior). If set, it will set arg0 explicitly. Depending on the `win-verbatim-args` argument the `arg0` argument will be quoted or not on Windows. This API mirrors what the [node.js](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) API does.

I have respective PRs ready.
Implementation: https://github.com/rakudo/rakudo/pull/4166
Tests: https://github.com/Raku/roast/pull/714
Documentation: https://github.com/Raku/doc/pull/3784

I guess this problem is at the bottom end of worthy of a problem-solving ticket and I don't expect much discussion to be necessary nor happening. I'll turn the above into a problem-solving PR once I get at least one approval / request for PR. (Why shouldn't we follow the process at least once correctly?)

**Comment by vrurg** [comment]
I don't see a need for problem-solving PR. Not every problem requires it. If we do it for every single task then eventually it'll end up with pile of papers no one really needs and no one really knows how to find the required one.

Also, your solution seemingly follows [compatibility guidelines](https://github.com/rakudo/rakudo/blob/master/docs/articles/2016-02%20Proposed%20Perl%206%20Versioning%20And%20Compatibility%20Guidelines.md#coresetting-changes-that-are-exempt-from-compatibility-concerns). Therefore we can just proceed with merging and then close this issue.

**Comment by patrickbkr** [comment]
Understood. Thanks for the compatibility guidelines link, I didn't know about those. Closing.
