### ISSUE TITLE
conf.raku.org DNS record

### ISSUE THREAD

**Issue by ash** [Raku/problem-solving#269]
Can you please point `conf.raku.org` to `159.69.82.96`. I am planning to launch the conference site on March 10-15.

**Comment by lizmat** [comment]
Feels weird pointing to it now, while it still has the PerlCon 2019 info up there?

**Comment by ash** [comment]
@lizmat if you use the IP then it was indeed redirecting to PerlCon. But that's not difficult to reconfigure, which I did now.

We do not have to make it public before it is finally ready. Still to do: SSL certificate, email settings, registration process, some other changes. At least some of these items require the domain to be ready first.

**Comment by maettu** [comment]
@ash I am confused. 
https://github.com/Raku/problem-solving/issues/262#issuecomment-786437994
"I decided it is not yet time to make a conference."

And another comment, that seems deleted and talks about "cancel culture".

And now announcing a conference in August and a call for paper by March 15?

**Comment by ash** [comment]
@maettu Yes, indeed, maybe it is very unclear from the short note, but the original idea was to have a combination of the conference and creating TRF (see the original description). It is too early to do that as TRF is about to be a part of TPF/YAS, which damaged a EU Perl conference in the past. I completely disagree with (or even shocked by) the proposed TRF solution and by the way it was achieved, so I am trying to find a way to keep things separately.

Recall last year's thread about [splitting the conferences](https://www.reddit.com/r/rakulang/comments/doe6ny/conference_split_and_more/). It is repeating now on the level of the foundation.

There were no plans to cancel *the conference itself*, as Raku *needs* it. Neither there is any need to keep an open ticket where nobody would like to take responsibility to build any software.

Let us just return to the technical ("I'd better coding") aspect of setting a DNS record.

**Comment by ash** [comment]
Hi @rba just a kindly reminder that this ticket is not yet resolved. Thanks.

**Comment by lizmat** [comment]
The official procedure for issues in this repo, is to have a PR to resolve the issue.  There's no way to approve anything in the issue :-)  So in that sense, this is maybe the wrong place to ask.

@ash: In any case, I'll put it on the agenda of the RSC meeting tomorrow, so there should be a resolution about this by Sunday at the earliest.  Which should still be in time for the timeframe you had in mind for going more public with it?

**Comment by rba** [comment]
Done

**Comment by lizmat** [comment]
@rba Thanks!
