### ISSUE TITLE
new Coercion protocol creates an opportunity for more ergonomic coercions 

### ISSUE THREAD

**Issue by codesections** [Raku/problem-solving#270]
I very much like the new coercion protocol that @vrurg has added to Raku.  This makes working with user-defined types much easier; now, all of the following work (adapted from [this blog post](https://vrurg.github.io/2020/11/16/Report-On-New-Coercions):

```raku 
class IntBox {
    has Int:D $.value is required;
    multi method COERCE(Int() $value) { self.new: :$value}
}

sub foo(IntBox() $v) { say $v }

foo 1;
foo '2';
my $three = 3;
foo $three;   # wow, nifty!
```

However, now that all of that is so easy, I very much want to be able to coerce types myself just as easily as a function can.  For example, I'd like to be able to coerce `$three` into an `IntBox` myself and then be able to pass it into 

```raku
sub bar(IntBox $v) { say $v.raku }
```

If I try to do so naively (i.e., as though `IntBox` were a type built in to Raku) I might try 

```raku
# bar $three.IntBox; # THROWS X::Method::NotFound
```
But that clearly won't work – `IntBox` didn't exist when `Int` was defined.

This doesn't mean that I _can't_ call `bar` with `$three` (this is Raku, so of _course_ we can find a way to be clever :grinning:).  Both of these work:
```raku
bar my IntBox() $ = $three;
bar IntBox().^coerce($three);
```
But both of these feel a bit like workarounds rather than a core part of the syntax, and both would be difficult to explain to new users without getting into some fairly advanced concepts.  I believe that the new coercion protocol gives us the opportunity to do significantly better.

**Comment by codesections** [comment]
To solve this problem, I suggest adding two new methods to `Any` (or potentially to `Mu`)  that use the new coercion protocol to support manual coercions.  These two methods would allow the following two lines to work:  

```raku
bar IntBox.from($three);
bar $three.into(IntBox);
```
Why both `into` and `from` instead of picking one?  Because it allows the user to control word order and and thus emphasis within their program, allowing for clearer code.

I look forward to hearing your thoughts.  My current plan is to wait a few day and then to submit a PR with a slightly more formal version of this solution, as modified by the conversation in this thread.  But that could certainly change, depending on your thoughts.

**Comment by jnthn** [comment]
The syntax `TypeName($value)` is the syntax for coercion.

```
$ cat x.p6
class IntBox {
    has Int:D $.value is required;
    multi method COERCE(Int() $value) { self.new: :$value}
}

dd IntBox(3);

$ raku x.p6
IntBox.new(value => 3)
```

**Comment by codesections** [comment]
> The syntax `TypeName($value)` is the syntax for coercion.

That is… news to me and **very** good to know.  And is definitely missing from the [relevant section of the docs](https://docs.raku.org/language/typesystem#Coercion), which says:

> Turning one type into another is done with coercion methods that have the same name as the target type. This convention is made mandatory by Signatures. The source type has to know how to turn itself into the target type. To allow built-in types to turn themselves into user defined types use [augment](https://docs.raku.org/language/variables#The_augment_declarator) or the [MOP](https://docs.raku.org/language/mop).

I take it that we should _not_ be recommending that users use `augment`/the MOP here?  I think adding `into` and `from` methods would be better than encouraging `augment`, which was part of the motivation for this issue.  But it sounds like the `TypeName($value)` syntax removes the need for either.

Assuming I've understood you correctly and that no one else jumps in to say that Raku should add `into` or `from` just for clarity/to allow users to control word order, I'll probably close this issue and open a Raku/doc issue to document that syntax.  Thanks, @jnthn!

**Comment by vrurg** [comment]
> Assuming I've understood you correctly and that no one else jumps in to say that Raku should add `into` or `from` just for clarity/to allow users to control word order, I'll probably close this issue and open a Raku/doc issue to document that syntax

@codesections You're somewhat [late](Raku/doc#3807) on this. :)
