### ISSUE TITLE
Preserving / Accessing Raku IRC Log History

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#280]
The Raku Programming Language has a long history of development.  A large part of that history is preserved in blog posts: keeping that history is hopefully possible with the [CCR](https://github.com/raku/CCR#the-raku-collect-conserve-and-remaster-project) project.

Another large part of the Raku history happened on IRC.  Currently, these logs are kept on an external website: https://colabti.org.  Although this is a great service, it is a service that has been without significant development for the past **13** years.  And it has been offline for a few days in the past without a clear indication of who to call to get it back up again.

I think the Raku community needs to be holding up its own in that respect.

I therefor propose the following:

- keep a log of all Raku IRC channels in a Github Repo under the "Raku" organisation.  Note that I have such a repo already for testing: it would simply be a matter of moving that here

- have a Raku channel logger running doing our own logging.  Note that I have developed the [IRC::Client::Plugin::Logger](https://modules.raku.org/dist/IRC::Client::Plugin::Logger:cpan:ELIZABETH) for that purpose (logging in Colabti format), and that has been running stable internally as `LizBot` on the #raku, #raku-dev and #moarvm channels for a week now.  I will be able to run that service locally for the foreseeable future.

- have an API to access the IRC logs.  Note that I have developed [IRC::Log::Colabti](https://modules.raku.org/dist/IRC::Log::Colabti:cpan:ELIZABETH) and [IRC::Channel::Log](https://modules.raku.org/dist/IRC::Channel::Log:cpan:ELIZABETH) for that purpose.

- have a Cro-based server / webservice to provide a web presence of these logs in a way that does not look like it's 1995 (or 2008 for that matter).  I'm working on that, but could use some help with the HTML / Javascript frontend.  I will be able to run this service in the short-term, possibly even in the longer term.

All of this should result in a service to the Raku community, and be a nice showcase of the use of the Raku Programming Language (no `nqp::` ops were involved in any of the code written so far).  And possibly, if properly containerized / configurable, it could well be an app that other communities that use IRC channels would want to use as well.

**Comment by lizmat** [comment]
See also the points I made in https://www.reddit.com/r/rakulang/comments/myumxo/whats_everyone_working_on_this_week_2021_week_17/

**Comment by lizmat** [comment]
In order to create an never ending scrollable view of the IRC logs, the web server API should be able to produce JSON for a given number of messages before / after a given message.

**Comment by AlexDaniel** [comment]
>  Although this is a great service, it is a service that has been without significant development for the past 13 years. And it has been offline for a few days in the past without a clear indication of who to call to get it back up again.

If anything happens, talk to user `feb` on `#irclogger`. They respond very quickly and usually all issues are resolved in a timely manner. Moreover they were kind enough to spend time on importing logs from the previous logging server when it went down. Not to discourage you from creating a new logger, just pointing out how to get help with the current one.

**Comment by patrickbkr** [comment]
What's the reason for keeping the logs on GitHub? Intuitively I'd kept them in plain text files on our own infrastructure (and maybe as backup on GitHub) as they don't really need any versioning. Or is that already what's happening?

**Comment by lizmat** [comment]
> Or is that already what's happening?

To my knowledge, nothing is kept on Raku infrastructure at this moment.  If you'd consider Moritz' server as "our infrastructure", then it was until he decided to not run the risk of any GDPR issues.

> kept them in plain text files

This is how they exist on the Colabti site, and now in my private repo, one day per file.

> maybe as backup on GitHub

Well, if we're going to keep them on Github, why not make them publicly accessible as well.  And make that the primary "backup" ?

In any case, there have been cases when the logs have been adapted, e.g. to remove spam.  Keeping them on Github thus allows keeping track of changes.

**Comment by jnthn** [comment]
@lizmat Is this issue resolved through the merge of #281?

**Comment by lizmat** [comment]
No.  There will be another pull request once the temporary server is production ready.  That PR will be about the integration into the rest of `raku.org`.  In honor of the original IRC log web site, I was thinking of using the URL "irclogs.raku.org".

**Comment by gfldex** [comment]
"chatlogs.raku.org" may be better. We already got a Discord server and more platforms may follow.
