### ISSUE TITLE
Priority of `let` and `temp` operators give them WAT behavior

### ISSUE THREAD

**Issue by vrurg** [Raku/problem-solving#292]
`let` and `temp` operators are currently have looser priority than `.=` and `.`. This results in somewhat confusing behavior in cases like:

```raku
my $foo = "foo";
{
    let $foo .= &{ Nil };
}
say $foo; # Nil, but despite of DWIM suggesting "foo" here
```

`(let $foo) .= &{ Nil }` fixes the situation, but looks no so good. 

A follow-up to rakudo/rakudo#4486.

**Comment by vrurg** [comment]
The solution is quick and simple, see rakudo/rakudo#4492. It is passing both tests and spectests. Yet, I'm not fully certain if there are no overlooked side effects.

First of all, this makes the operators to "jump over" many other groups, like junctives, additives, etc. Perhaps this is ok because `let ++$foo` is an error, but `my $bar = let $foo + 42` would likely follow DWIM.

Somewhat mixed feeling I have about `let $foo.method`, but then again: it would be kind of weird for `let` to operator on a scalar returned by `method`, if it returns a scalar.

So, overall I'd be in favor of raising the priority. Then the next question is if we can do it for `6.c` (roast allows it), or should it be a `6.e` change? Again, unless blin would report a problem in the ecosystem, I'd rather keep the code simple and have `6.c` has it.

**Comment by vrurg** [comment]
With regard to the priority, I made a mistake and the priority leap proposed in rakudo/rakudo#4492 doesn't cover `++`. Though I think it should to make `let $foo++` do what it would be expected to. I will update the PR according to this consideration. Yet, the priority must remain lower than that of the methodops like `.`, `.&`, etc.

**Comment by raiph** [comment]
A nit; your initial example should s/Nil/(Any)/ in the last line:
```
my $foo = "foo";
{
    let $foo .= &{ Nil };
}
say $foo; # (Any), but despite of DWIM suggesting "foo" here
```

(In my examples I had used `my $foo is default(Nil) = "foo";`.)

**Comment by vrurg** [comment]
`is default` doesn't change the event flow anyway. It only affects the resulting value of `$foo` and, correspondingly, what typeobject gets returned by the block.

**Comment by vrurg** [comment]
I consider rakudo/rakudo#4492 as a solution to this issue. If it doesn't cause a major non-fixable breakage in the ecosystem then I'm going to close the issue soon after a pre-release blin run.

**Comment by Altai-man** [comment]
I did a Blin run this week, no breakage.

**Comment by vrurg** [comment]
I have missed the last note. Ok, closing then.
