### ISSUE TITLE
Consider renaming default branch from master to main

### ISSUE THREAD

**Issue by coke** [Raku/problem-solving#298]
Please consider renaming the default branch for existing Raku-related repositories from master to main.

https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by lizmat** [comment]
FWIW, I think the plan is to have the RakuAST branch become "main" at some point for rakudo/rakudo.

But generally the problem is really the number of outstanding PRs that would get invalidated by the default branch change, no?

**Comment by coke** [comment]
I think GitHub automatically fixes those.

**Comment by lizmat** [comment]
They do?  That would be excellent.  It was my impression that they didn't, so a reason not to just move forward on this.

**Comment by coke** [comment]
https://github.com/github/renaming#renaming-existing-branches

**Comment by vrurg** [comment]
Closing as resolved. #356
