### ISSUE TITLE
No easy way to inspect distributions

### ISSUE THREAD

**Issue by skaji** [Raku/problem-solving#306]
## a short description of the problem

I think there is no easy way to inspect distributions.

## more details

Let's say we use `Module` in our script:

```raku
use Module;

my $mod = Module.new;
...
```

Sometimes I want to inspect the distribution which `Module` belongs to.
Especially I want to know:

* distribution name
* version and auth of distribution
* resource files of distribution

But currently there is no easy way to do it, I think.

**Comment by coke** [comment]
There is this, which is working on the ecosystem lists, not what's installed:

```
$ zef info App::Uni
- Info for: App::Uni
- Identity: App::Uni:ver<1.0.2>
- Recommended By: Zef::Repository::LocalCache
- Installed: No
Description:     command-line utility to find or display Unicode characters
License:         Artistic-2.0
Source-url:      git://github.com/coke/p6-uni.git
Provides: 1 modules
Depends: 0 items
```
