### ISSUE TITLE
Make Junction a value object.

### ISSUE THREAD

**Issue by vrurg** [Raku/problem-solving#311]
Inspired by rakudo/rakudo#2814 and #297 ([this comment of mine](https://github.com/Raku/problem-solving/issues/297#issuecomment-962220387) in particular).

While playing with possible ways of resolving rakudo/rakudo#2814 I realized then when basically fixed, `classify` method creates single entry per each `Junction` instance, no matter some are actually the same. But it would really make big sense if `any(True, False)` and `any(True, False)`, or `one('a', 'b')` and `one('a', 'b')` were considered same values.

**Comment by vrurg** [comment]
It does make sense for `Junction` to be a value object because it is both immutable and it deconts its eigenstates. Test implementation doesn't seem to produce any spectest fallout.

**Comment by jnthn** [comment]
fwiw, I don't see any downsides to the proposed change.
