### ISSUE TITLE
Wrong behavior is specced for classify method

### ISSUE THREAD

**Issue by vrurg** [Raku/problem-solving#312]
rakudo/rakudo#2814 describes classify behavior which is considered weird, to say the least. The produced output is highly confusing, if not totally wrong. For `<a b c d e f>.classify( * eq 'a'|'c'|'f' )` one would expect `'a'` to be classified as _True_, but it also appears in _False_.  Same applies to `'c'` and `'f'`.

**Comment by vrurg** [comment]
I'm proposing a solution where the method would classify over junctions, produced by the tester code, without collapsing them and autothreading. So, where `'a'` is encountered it would be classified as `any(True, False, False) => ['a']`. Together with #311, i.e. when `Junction` becomes a value object, the classification would produce correct classes for the same junctions. For example, if `'a'` is encountered more than once in the original list, there there will be single entry of `any(True, False, False) => ['a', 'a']`, instead of what happens with a non-value `Junction` which results in two classification entries for each individual junction instance produced by the tester: `any(True, False, False) => ['a'], any(True, False, False) => ['a']`.

The biggest problem about the proposed behavior is the fact that the incorrect behavior is actually currently specced in _t/spec/S32-list/classify.t_. 

The second problem is that the proposed behavior would require the classification `Hash` to be parameterized with `Mu`-typed keys and this also breaks this test and _t/spec/S32-list/categorize.t_.

The latter issue should be minor because `Mu`-typed keys actually rather extend the range of allowed values, than adds more restrictions. So, unless there is a Blin fallout, it should be doable. Moreover, it fixes _t/spec/S09-hashes/objecthash.t_ where two tests are currently dying.

It's not that simple with the first problem because it's would be a rather major change to 6.c spec. But my proposal would be the same: give it a try and see if any module in the ecosystem relies on the wrong behavior. If there is any then a decision is to be made about the fate of this change.

**Comment by vrurg** [comment]
A code sample and outcome with my current implementation of #311 and this proposal together:

```raku
<a b a c a d e f e>.classify( * eq 'a'|'c'|'f' ).say;
# {any(False, False, False) => [b d e e], any(False, True, False) => [c], any(False, False, True) => [f], any(True, False, False) => [a a a]}
```

**Comment by codesections** [comment]
I agree that the current behavior is a problem and I _tentatively_ agree with the proposed solution (pending Blin fallout/push back from others.)

(A note for other readers: the Rakudo issue linked in the OP (rakudo/rakudo#2814) is more than just a description of the problem – it also contains discussions of other potential solutions and why they wouldn't be ideal.  In particular, before reading that thread, I was inclined to think that &classify _should_ collapse junctions, but the points raised in that thread changed my mind.)
