### ISSUE TITLE
Our symbol resolution implementation is totally counter-thread-safe

### ISSUE THREAD

**Issue by vrurg** [Raku/problem-solving#323]
Short intro: `require` my result in broken symbol tables.

A little longer.

Rakudo implementation of symbol tables is heavily based upon `Hash`/`Map`. This is true for both `Stash` and `PseudoStash`. When it comes to dynamic symbol resolution (`::()`) everything is more or less OK because `BOOTHash` is read-safe. But as soon as we add `require` there is non-zero chance of conflicting read/write taking place in a multi-threaded application.

**Comment by vrurg** [comment]
I don't have any solution for this so far. The biggest players here are `PseudoStash`, `&REQUIRE_IMPORT`, and `&INDIRECT_NAME_LOOKUP`.

There is no workaround from user code perspective. One could lock-protect symbol lookups and `require` within their application, but can't take care of 3rd party modules.

A module could also use a lock, but it would be different from what user code is using, drawing it useless.

From the compiler perspective, it is noticeable that `GLOBALish` is heavily used by the code working with symbols. So, the first impression that a global lock must be used. This would help with mutually exclusive invocations of `&REQUIRE_IMPORT` and `&INDIRECT_NAME_LOOKUP`, but barely useful when `PseudoStash` is involved and used by user code. 

Though the problem with `PseudoStash` is solvable if the global lock becomes part of our public API and is properly documented. But this would also require Raku specs to be updated as the changes of such scope cannot remain compiler-specific.

Sorry for somewhat chaotic text, but I'm in the process of realizing the extent of the problem.

**Comment by lizmat** [comment]
pinging @jnthn

**Comment by jnthn** [comment]
Given writes to symbol tables are comparatively rare, one option is to always clone the underlying hash (that the `Stash` references), change it, and install the new version. That way, reads don't need protecting, and writes can be serialized either by a lock for that purpose or by CAS on the attribute of the `Stash` holding the underlying hash.

**Comment by lizmat** [comment]
I do think the `nqp::clone` needs protecting, though, doesn't it?

**Comment by jnthn** [comment]
There are two objects involved in a clone, the source and the target. A `clone` reads the source, which may be shared globally, and writes into the target, which is referenced only by the `clone` implementation. Since it only reads the source, then so long as all changes are doing a `clone` first, there's no read/write conflict.

**Comment by niner** [comment]
If the nqp::clone is not protected by the lock, then what is? Without that protection, two competing threads may clone the same original hash, make modifications to their local copy and then replace the original with their extended copy. But that will mean that whoever replaces last gets their change in while the other change is lost.

**Comment by jnthn** [comment]
> Without that protection, two competing threads may clone the same original hash, make modifications to their local copy and then replace the original with their extended copy.

As I said, writes need to be serialized. Not just the clone, but from pre-clone attribute read to post-clone installation. That can be done via a lock or via OCC.

**Comment by jnthn** [comment]
To clarify further, there are two things we want to achieve:

1. Not violating the contract that a (VM-provided) hash may not be read concurrent with writes done by other threads, or be written to by multiple threads at once
2. Not losing changes to the stash

The "clone, change the clone, install the clone" approach only achieves 1. Some kind of change serialization solves 2.

**Comment by niner** [comment]
I'd guess that changes very rarely conflict. After all compilation and loading modules (the big writers to stashes) mostly happen serialized.

Given that, going the CAS way would be more efficient: `cas $!storage, -> $orig { my $new := nqp::clone($orig); nqp::bindkey($new, $key, $value); $new }`

**Comment by lizmat** [comment]
Wouldn't that potentially be a deadlock with 2 threads trying to put in different values?

**Comment by niner** [comment]
Why would it?

**Comment by jnthn** [comment]
> Wouldn't that potentially be a deadlock with 2 threads trying to put in different values?

Assuming you mean the CAS approach: if one "transaction" under CAS fails it's because a different one succeeded, so there's a global progress bound. (There's *not* a local progress bound, which is a failure mode of these approaches, but primarily in situations where the transactions differ in size and the rate of conflicts is high.)

**Comment by lizmat** [comment]
ok, gotcha both :-)

**Comment by vrurg** [comment]
This discussion has cleared up some of my mind. Perhaps, I would manage to get thing done right.

Just one note so far: CAS is not an option to guarantee atomicity. First, `$!storage` on Map is not a container.

Second, the most typical course of events would be to clone a stash -> merge symbols -> replace. Merging is not cheap. If, by chance, we get into a situation of multiple replacements the cost of CPU time would be even higher than one could expect. I was experimenting with `AttrX::Mooish` and found out that `cas` results in 4 time higher _usr time_ even though the protected code is much cheaper on average, than symbol merging we'd need to do under each `cas` loop.

**Comment by vrurg** [comment]
rakudo/rakudo#4917 resolves this issue.

**Comment by niner** [comment]
As always with complex performance questions, the only way to know what's 
better will be to benchmark.
