### ISSUE TITLE
Taking responsibility for Raku Documentation issues

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#324]
After many years, JJ Merelo has decided to step back from taking responsibility for the documentation of the Raku Programming Language.

Therefore the Raku Community is looking for a person willing to take on this role, which would consist of:
- ensuring consistency in the Raku documentation
- ensuring the Raku documentation is up-to-date
- being a tie-breaker on documentation matters if no consensus could be reached

On behalf of the Raku Community, the Raku Steering Council would like to thank JJ for all the work they've done for Raku, and its documentation in particular.  For many, many years!  In the hope that JJ will continue to be a pillar of the Raku Programming Language!

**Comment by coke** [comment]
Thanks to JJ for their work over the years.

I am happy to volunteer on the three points noted by lizmat above.

**Comment by coke** [comment]
I am trying to setup a call (skype/zoom/etc.) with anyone interested in working on the docs site (newcomers, folks with work in progress, everyone) so we can look at planning, setting expectations, etc.

If anyone is interested in attending, please add a note to:

https://github.com/Raku/doc/wiki#meeting

or stop by `#raku-doc` on IRC.
