### ISSUE TITLE
Adding head, skip, tail as subroutines

### ISSUE THREAD

**Issue by 2colours** [Raku/problem-solving#328]
Hello,
this has been mentioned on chat a couple of days ago.
It would be nice to have head, skip and tail as subroutines with the iterable as their last parameter, similarly to grep and map.
This would both increase consistency (why _shouldn't_ they work, if grep and map do work?) and the usefulness off the feed operators, since this would allow us to write
1, 3 ... * ==> grep &some-condition ==> head 20
and similar code.

**Comment by patrickbkr** [comment]
@SmokeMachine Is this related work of Reds respective operators? Do they match?

**Comment by lizmat** [comment]
I've also created a module to allow for this functionality in older Rakudo versions:

https://raku.land/zef:lizmat/head-skip-tail  (aka https://github.com/lizmat/head-skip-tail)
