### ISSUE TITLE
The semantics of >>.foo feel wrong and possibly need changing

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#345]
This has been instigated by https://github.com/rakudo/rakudo/issues/5057 .

I've come to the conclusion that my fix for that issue is either the wrong fix, or we need to rethink the semantics of >>.foo.  The documentation currently states:

> This is the hyper method call operator. Will call a method on all elements of a List out of order and return the list of return values in order.

Now, clearly, that doesn't work for `Associative`s, as the "elements" of `Associative`s are `Pair`s:
````
$ raku -e  'my $b := <a b c d c d>.BagHash; $_-- for $b; dd $b' 
Cannot resolve caller postfix:<-->(Pair:D);
````
So `Associative`s are handled differently by calling the operator on the *values* of the `Associative`.

Now let's get back to the original example:
````
$ raku -e 'say <a b c d c d>.BagHash>>--'                
BagHash(c d)
````
This now returns what the op expected.  But that expectation was actually *wrong*, because if we do something similar with an array that is created on the fly:
````
$ raku -e 'say [1,2,3,4,5]>>--'
[1 2 3 4 5]
````
**will return a List of the return values in order**  And since `&postfix:<-->` returns the original value, the return value is actually a *copy* of the original array, and the decrements that have been done, are lost in the ether.  If we want to be consistent with that behaviour, then:
````
$ raku -e 'say <a b c d c d>.BagHash>>--' 
BagHash(a b c(2) d(2))
````
And those decrements would be lost in the ether as well.  And would be contrary to expectations of the op as well.

**Comment by lizmat** [comment]
Related: https://github.com/rakudo/rakudo/commit/d0ec99a861

**Comment by frithnanth** [comment]
OK, I understand that it's about the difference between post and pre-decrement.
Obviously (now :-) ) post-decrement returns the original value, then decrements the content of the variable. The pre-decrement does it in the opposite order.
So
```bash
$ raku -e 'say [1,2,3,4,5]»--'
[1 2 3 4 5]
```
while
```bash
raku -e 'say --«[1,2,3,4,5]'
[0 1 2 3 4]
```
Yet doing the same on a BagHash still returns strange results using the stock Rakudo v2022.07:
```bash
$ raku -e 'say --«<a b c d c d>.BagHash' 
BagHash(d)
$ raku -e 'say --«<a b c d c d>.BagHash'
BagHash(c)
$ raku -e 'say --«<a b c d c d>.BagHash'
BagHash(c d)
```
(Those are really three successive tests on my computer :-o )

**Comment by lizmat** [comment]
That is what commit https://github.com/rakudo/rakudo/commit/d0ec99a861 fixed: rakudo HEAD now says:
````
$ raku -e 'say --«<a b c d c d>.BagHash'
BagHash(c d)
````
as expected.

**Comment by 2colours** [comment]
Quoting from https://docs.raku.org/language/operators#index-entry-hyper_%3C%3C-hyper_%3E%3E-hyper_%C2%AB-hyper_%C2%BB-Hyper_operators:

> Hyper operators can work with hashes. The pointy direction indicates if missing keys are to be ignored in the resulting hash. The enclosed operator operates on all values that have keys in both hashes.

I think it makes sense that >>. behaves similarly, operating on the values of the Associative data types. I'm not sure if the issue was concerned with this approach but maybe it's good to point out that this seems to derived from related documented behavior.

There are still problems with the semantics/documentation of hyper operators, I wanted to open an issue for that, getting into it now.

**Comment by raiph** [comment]
@2colours 

> Quoting from [doc]:
>
> The pointy direction indicates if missing keys are to be ignored in the resulting hash. The enclosed operator operates on all values that have keys in both hashes.

Aiui that doc is about binary op hypers ("both hashes"), not unary ops like this issue. I'm not seeing a connection.

**Comment by 2colours** [comment]
@raiph 

I am making the connection by saying:

> I think it makes sense that >>. behaves similarly, operating on the values of the Associative data types.

Since it seemed the "operating on the values" part may not be written down for the >>. call.
