### ISSUE TITLE
What to do with https://twitter.com/raku_news ?

### ISSUE THREAD

**Issue by moritz** [Raku/problem-solving#348]
I've been running https://twitter.com/raku_news for nearly 6 years now, and it has a bit more than a thousand followers.

Given the recent direction of twitter's content moderation and monetization plans, I'm no longer willing to interact with twitter on a regular basis.

I'd be happy to transfer this account to a person or email address of your choice, or shut it down. I'm also open to other proposals that don't involve me operating it long term.

**Comment by melezhik** [comment]
> Given the recent direction of twitter's content moderation and monetization plans

What's wrong with that?

**Comment by lizmat** [comment]
@melezhik I don't think that that is important.

What is important, is that @moritz is looking for someone to take over the job of (re)tweeting news about the Raku Programming Language.  That alone should be enough for someone in the community to step forward :-)

**Comment by rba** [comment]
@moritz: Sorry for hijacking this, but my thoughts are just too similar.
During name change I've registered @raku_lang on twitter (https://twitter.com/raku_lang). Mostly to make sure it's not taken by any non community member. I've used the account mostly for retweeting.

Maybe it's worth to consolidate efforts here. I will hand it over to anyone who likes to use it or just like to keep it reserved.

**Comment by patrickbkr** [comment]
>> What's wrong with that?
> @melezhik I don't think that that is important.
I agree it's off topic. Still I'm interested. Not as a justification, but because it could be relevant for me as well. Could someone provide a link or similar where to read up on this?

**Comment by moritz** [comment]
What's wrong? People like Tony Braxton getting whole volleys of hate messages and no interventions from twitter, simply for being a public black woman.

In general, private companies are less accountable than public ones, and I don't want to wait until the drama plays out in full, or until the hate reaches myself.

Regarding the monetization: there has been speculation that Musk wants to turn twitter into an "everything app", meaning adding lots of features, including payments processing, and taking a cut from that. That's simply not something I want my social media to be, independently of whether there is something wrong with that.

I realize that these are all pretty soft  reasons, but I don't want to give the person the benefit of a doubt who publicly called a cave rescue diver a pedophile, without any evidence, just because his ego was bruised.

**Comment by lizmat** [comment]
FWIW, I've registered `https://fosstodon.org/@rakulang` to be the official Raku Programming Language feed.  And it's now in use.

**Comment by lizmat** [comment]
@moritz @rba if you could post a message about this on your Twitter feed, and then request a backup, then we can freeze the Twitter feeds as far as I'm concerned.

**Comment by melezhik** [comment]
So, practically speaking, should Raku authors now advertise their news on fosstodon.org, not on twitter? ))) or this only affects official rakudo/raku news?

**Comment by lizmat** [comment]
you can post it anywhere on Mastodon, I'll be monitoring the #RakuLang tag

I'll also keep monitoring Twitter for the time being, but don't know for how long

**Comment by nxadm** [comment]
Why not crossposting from Mastodon?

(E.g. with https://crossposter.masto.donte.com.br)

**Comment by rba** [comment]
I took @moritz pinned comment and tweeted and pinned it https://twitter.com/raku_lang/status/1593243663408451585 as well.

**Comment by lizmat** [comment]
Closing this now.  Please re-open / comment if you disagree.
