### ISSUE TITLE
Helper function on SetHashes

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#35]
See https://github.com/rakudo/rakudo/pull/2942

Perhaps similar helper functions could be useful on `BagHash`es (and `MixHash`es?) as well.  But probably should then be called `.add` and `.subtract`

**Comment by AlexDaniel** [comment]
> ```%sethash{$_} = True for @to-be-added;```
> ```%sethash.set(@to-be-added);```

I don't think we should be adding stuff purely for speed reasons when other ways of doing the same thing are not ironed out in terms of performance.

For example, I can see other ways of doing the same thing. Like:
```
%sethash{@to-be-added} X= True;
```
Which is currently much slower, but there has to be a way to make it as fast as the proposed `.set()` method, right?

Also, it seems that good performance is already achievable with something like this:
```
%sethash ,= SetHash.new(@to-be-added);
```
Although I'm not sure if it is fully identical to the proposed .set method, and if it is as fast?

**Comment by lizmat** [comment]
my @a = ^10; my %s is SetHash; %s ,= SetHash.new(@a); dd %s.elems   # 2

That should have been **10**.

**Comment by lizmat** [comment]
Some benchmarks / readability comparison:

    $ 6 'my @a = ^100000; { my %s is SetHash; %s{$_} = True for @a; say now - ENTER now }'
    0.5418981

    $ 6 'my @a = ^100000; { my %s is SetHash; %s{@a} = True xx *; say now - ENTER now }'
    0.5311904

    $ 6 'my @a = ^100000; { my %s is SetHash; %s.set(@a); say now - ENTER now }'
    0.11501774

**Comment by vrurg** [comment]
@lizmat what is the current status of this? Is it still planned?

**Comment by lizmat** [comment]
I guess either it is up to @jnthn to decide, or we need to take a vote on it?

The conflicts should be easy to resolve.

**Comment by vrurg** [comment]
That's a question. We can't rely upon Jonathan on each end every case. As it was said, he is a scarce resource. But we probably need a collective decision making procedure. I'd try to think out something on this.

**Comment by jnthn** [comment]
> We can't rely upon Jonathan on each end every case

No, but language design things probably are one of the things I can most usefully opine on. Design by what can win a vote isn't going to produce much consistency.

Some questions:

1. Were `push` and `append` considered? For example, we have `Hash.push` and `Hash.append`, which seem to be in this very space, but not on `SetHash` etc.
2. I wonder if we're missing a "single argument rule" style thing here, so that `∪=` could potentially do the job.
