### ISSUE TITLE
RakuDoc GAMMA revision open

### ISSUE THREAD

**Issue by finanalyst** [Raku/problem-solving#380]
Following from #375

The [github repo RakuDoc-GAMMA](https://github.com/Raku/RakuDoc-GAMMA) is now open for comments, suggestions, requests.

The comments in #375 were considered when completing the Beta revision.

The GAMMA review process is scheduled to complete on November 1, 2023.

**Comment by coke** [comment]
What are you expecting from me as the assignee?

**Comment by lizmat** [comment]
I think it was the template that did that.  It does that for documentation issues.

**Comment by finanalyst** [comment]
@coke It's part of the template and I wasn't able to unassign you. @lizmat  Thanks

**Comment by 2colours** [comment]
@zag maybe this could be interesting for you as well

**Comment by lizmat** [comment]
Closing since outdated.  Please re-open if you disagree.
