### ISSUE TITLE
Ecosystem content, quality and fragmentation issues.

### ISSUE THREAD

**Issue by AlexDaniel** [Raku/problem-solving#39]
Currently the ecosystem is very messy. To name some problems:
* Some modules simply do not work (a list with some false positives here: https://github.com/perl6/ecosystem-unbitrot/issues)
* Some modules are listed multiple times for no good reason ([example](https://user-images.githubusercontent.com/5507503/59534865-21b42b00-8ef8-11e9-8263-57d5345e033d.png))
* There are different modules with the same name (example: https://modules.perl6.org/search/?q=zeromq)
* And more, like modules with a lot of NYI stuff, or no tests, or simply abandoned repos

IRC discussion: https://colabti.org/irclogger/irclogger_log/perl6?date=2019-06-14#l399

I don't know what would be the best solution. There are different ideas floating around, like creating a new ecosystem with a better policy, or trying to clean the current one by adding some sort of purgatory for modules. I think we'd benefit from having a person who'd be able to focus on the ecosystem stuff and come up with some solution.

**Comment by AlexDaniel** [comment]
There's currently no label for ecosystem related stuff. I'd happily create one once someone applies to become a responsible dev (similarly to how it was done in https://github.com/perl6/problem-solving/pull/23).

**Comment by JJ** [comment]
More things:
* Modules in CPAN are not tested (except by Blin)
* There are [17 issues in ecosystem](https://github.com/perl6/ecosystem/issues), some of them included here. No one is paying  (much) attention to it, anyway.
* [There's no way to solve name disputes](https://github.com/perl6/ecosystem/issues/424)
* [Test modules are kept there forever](https://github.com/perl6/ecosystem/issues/391)

Also, I [refused to merge the several versions of DDt you mention](https://github.com/perl6/ecosystem/pull/403) and I was burned. Anyway, the next squashathon is going to be devoted to the ecosystem (actually, modules.perl6.org, but this could e included if necessary)

**Comment by JJ** [comment]
(I also apply for this position, if you want to take me)

**Comment by JJ** [comment]
(BTW, I think now that these "duplicate" modules should actually be there, because they are different releases of the same module).

**Comment by nxadm** [comment]
> Currently the ecosystem is very messy. 

Maybe it's because order is expected where it does not exist yet. I think that for a young language like Raku expecting a centralized up-to-date listing is a little too much too ask. I think like a model like

**Comment by nxadm** [comment]
Closed by accident.

**Comment by JJ** [comment]
Maybe it's about time to revive this issue. Most problems here are still outstanding. For starters, I would propose a simple thing: eliminate CPAN from the ecosystem. Main reason is that anything uploaded there is not tested in any way or form, not even conformation to the META6.json *de facto* standard. Apparently, it's impossible now to get new PAUSE nicks, or at least extremely complicated (and not clear). Plus it's simply not under our control, and there's no way to add any kind of functionality we might need (like, let's say, change the "perl6" directory to Raku). We got fez now, I would propose a 1-year schedule to deprecate CPAN for Raku modules.

**Comment by lizmat** [comment]
Closing in light of developments, see #316
