### ISSUE TITLE
Inbound P6/Raku URLs are currently broken

### ISSUE THREAD

**Issue by raiph** [Raku/problem-solving#413]
Gah. I did not want this published. But a keystroke seems to have published it. And it seems that GH will not let me delete it. I am deleting the content, which was a mess I was in the middle of sorting out. I will update it when I have something coherent.

**Comment by raiph** [comment]
Gah, I did not assign rba! I did not add the infrastructure label. do not know how to unassign rba. I am extremely grateful for all rba did for us. I did not mean to alarm anyone! :(

**Comment by rba** [comment]
LOL. Merry xmas.
