### ISSUE TITLE
TAP refers to Perl 6

### ISSUE THREAD

**Issue by coke** [Raku/problem-solving#416]
https://testanything.org/testing-with-tap/ has a link to perl but not raku.

the perl link https://testanything.org/testing-with-tap/perl.html has links for 5 and 6.

**Comment by lizmat** [comment]
PR submitted https://github.com/TestAnything/testanything.github.io/pull/180

**Comment by lizmat** [comment]
PR accepted and merged: https://testanything.org/testing-with-tap/ now shows Perl and Raku separately
