### ISSUE TITLE
%0 and &0 should probably be syntax errors

### ISSUE THREAD

**Issue by lizmat** [Raku/problem-solving#44]
This started off with:

    $ perl6 -e 'my $width = 4; printf("%0{$width}d", 42)'
    Use of uninitialized value element of type Any in string context.
    Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
      in block <unit> at -e line 1
    Your printf-style directives specify 0 arguments, but 1 argument was supplied
      in block <unit> at -e line 1

which, in my view, is a completely legit way of specifying a variable width `printf` format.

Turns out, this does not do what you mean.  Apparently, this is short for `%($/[0])`.

    $ perl6 -e '"abcd" ~~ m/(\w)+/; say %0'
    {a => ｢b｣, c => ｢d｣}

which looks nice, but with an odd number of captures, becomes:

    $ perl6 -e '"abc" ~~ m/(\w)+/; say %0'
    Odd number of elements found where hash initializer expected:
    Found 3 (implicit) elements:
    Last element seen: Match.new(list => (), from => 2, hash => Map.new(()), made => Any, pos => 3, orig => "abc")
      in block <unit> at -e line 1

It even gets weirder with `&0`:

    $ perl6 -e '"abc" ~~ m/(\w)+/; say &0'
    [｢a｣ ｢b｣ ｢c｣]

which, btw is also what `@0` and `$0` give.

I propose that `%N` and `&N` (where *N* is a 0..Inf) do **not** interpolate, and become syntax errors outside of interpolation.

**Comment by AlexDaniel** [comment]
FWIW, I didn't even know that @0 %0 &0 are allowed.

**Comment by lizmat** [comment]
I didn't either until someone pointed it out to me in a mail.  `@0` kinda makes sense, for the given example.  `%0` and `&0` definitely do not, in my opinion.
