### ISSUE TITLE
Clarifying dual-licensing on the site

### ISSUE THREAD

**Issue by drforr** [Raku/problem-solving#56]
In a recent conversation I had, a certain large company is apparently removing Perl 5 from their core distribution partially because it was under the AL. Making it clear that Perl 6 (as well as 5) can be dual-licensed under either the AL or GPL might help adoption by making it clear that both AL and GPL users are welcome.

**Comment by coke** [comment]
RIP @drforr.

I am not sure this note is correct. As far as I understand, Raku (even as Perl 6) was never available under a dual license at the user's choice, it was always Artistic 2.0.

I think we can reject this ticket. @codesections, @lizmat ...

**Comment by lizmat** [comment]
Well, doesn't AL 2.0 imply dual licensing?  I think @drforr was referring to the original AL?

**Comment by coke** [comment]
I don't see any mention of GPL in the AL2.0 text.

**Comment by coke** [comment]
Yes, but re-licensing is not dual licensing.

**Comment by patrickbkr** [comment]
(I think irrelevant to this ticket, but) it seems Perl5 acually is dual licensed under AL and GPL: https://dev.perl.org/licenses/

**Comment by patrickbkr** [comment]
Back to the original issue, I agree with @coke that this can be closed, as there is no option to license Rakudo as anything else than AL2.

**Comment by coke** [comment]
No comments in the last 2+ years, closing ticket. Regards.
